In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [2]:
csv_file = Path("../data/customer_support_tickets.csv")
csv_f = "../data/customer_support_tickets.csv"
print(csv_file)
print(csv_f)

df = pd.read_csv(csv_file)
df.head()

..\data\customer_support_tickets.csv
../data/customer_support_tickets.csv

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [3]:
pd.set_option('display.max_colwidth', None)

#### Embedding preprocess

In [5]:
df['Ticket_Description'] = df.apply(lambda row: str(row['Ticket Description']).replace('{product_purchased}', str(row['Product Purchased'])), axis=1)

print(df[['Ticket Description', 'Ticket_Description']].head())

                                                                                                                                                                                                                                                                                                                                       Ticket Description  \
0                                          I'm having an issue with the {product_purchased}. Please assist.\r\n\r\nYour billing zip code is: 71701.\r\n\r\nWe appreciate that you have requested a website address.\r\n\r\nPlease double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.
1                                            I'm having an issue with the {product_purchased}. Please assist.\r\n\r\nIf you need to change an existing product.\r\n\r\nI'm having an issue with the {product_purchased}. Please assist.\r\n\r\nIf The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.
2                                                               I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\r\n\r\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.
3                                                                            I'm having an issue with the {product_purchased}. Please assist.\r\n\r\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.
4  I'm having an issue with the {product_purchased}. Please assist.\r\n\r\n\r\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.

                                                                                                                                                                                                                                                                                                                                 Ticket_Description
0                                             I'm having an issue with the GoPro Hero. Please assist.\r\n\r\nYour billing zip code is: 71701.\r\n\r\nWe appreciate that you have requested a website address.\r\n\r\nPlease double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.
1                                                      I'm having an issue with the LG Smart TV. Please assist.\r\n\r\nIf you need to change an existing product.\r\n\r\nI'm having an issue with the LG Smart TV. Please assist.\r\n\r\nIf The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.
2                                                                                          I'm facing a problem with my Dell XPS. The Dell XPS is not turning on. It was working fine until yesterday, but now it doesn't respond.\r\n\r\n1.8.3 I really I'm using the original charger that came with my Dell XPS, but it's not charging properly.
3                                                                         I'm having an issue with the Microsoft Office. Please assist.\r\n\r\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.
4  I'm having an issue with the Autodesk AutoCAD. Please assist.\r\n\r\n\r\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my Autodesk AutoCAD. It used to last much longer.

In [4]:
def cleaning_descrn(row):
    text = str(row['Ticket Description']).lower().strip()
    
    #find anything inside {{ }} or { } and replace it with the Product Name
    product = str(row['Product Purchased'])
    text = re.sub(r'\{+.*?product_?purchased.*?\}+', product, text)
    
    # Since we don't have a column for 'error_message' - doubt
    # text = re.sub(r'\{+.*?error_message.*?\}+', '?', text)
    
    # Removes html tags
    text = re.sub(r'<[^>]+>', ' ', text)
    
    # Removes \r, \n, #, _, and extra brackets - } ]
    text = text.replace('\r', ' ').replace('\n', ' ')
    text = re.sub(r'[#__{}\[\]]', ' ', text)
    
    text = text.lower().strip()

    # Shrink multiple spaces to one
    text = re.sub(r'\s+', ' ', text) 
    
    return text

df['Ticket_Description'] = df.apply(cleaning_descrn, axis=1)

In [ ]:
# Check if any other curly brackets exist in the data - yet to work on it
remaining_placeholders = df['Ticket_Description'].str.contains(r'\{.*\}')
df[remaining_placeholders]['Ticket_Description']

# 27, 59, 64,65,70,8398, 8416, 8421, 8441, 8447

In [ ]:

df.loc[[27, 59, 64,65,70,8398, 8416, 8421, 8441, 8447], 'Ticket_Description'].values

In [ ]:
df.head()

In [ ]:
# word count

df['word_count'] = df['Ticket_Description'].apply(lambda x: len(str(x).split()))

In [ ]:
plt.figure(figsize=(10, 5))
sns.histplot(df['word_count'], bins=50, kde=True)
plt.title('Distribution of Word Counts')
plt.axvline(x=128, color='r', linestyle='--', label='Common Embedding Limit')
plt.legend()
plt.show()

In [ ]:
# duplicates check

df[df['Ticket_Description'].duplicated()]['Ticket_Description']

In [ ]:
df['Ticket_Description'].duplicated().sum()

In [ ]:
df['Ticket_Description'].value_counts()[df['Ticket_Description'].value_counts() > 1]

In [ ]:
df.shape

In [ ]:
import seaborn as sns

df['word_count'] = df['Ticket_Description'].apply(lambda x: len(str(x).split()))

plt.figure(figsize=(8,5))
sns.histplot(df['word_count'], bins=30, kde=True, color='orange')
plt.title('Distribution of Word Counts')
plt.show()

print(f"Average words per ticket: {df['word_count'].mean():.2f}")

In [ ]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Combine all text into one giant string
all_text = " ".join(df['Ticket_Description'].astype(str))

wordcloud = WordCloud(width=800, height=400, background_color='white', max_words=100).generate(all_text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Top 100 Most Frequent Words in Raw Data')
plt.show()

#### TF-IDF preprocess

In [ ]:
df.info()

In [ ]:
df['Ticket Description']

### Duplicate analysis

In [13]:
df[df['Ticket Description'].duplicated(keep=False)]

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating,Ticket_Description
56,57,Alison Ford,mcgeebrandon@example.org,69,Male,Autodesk AutoCAD,2021-12-22,Technical issue,Software bug,I'm having an issue with the {product_purchased}. Please assist. I've noticed that the issue occurs consistently when I use a specific feature or application on my {product_purchased}.,Pending Customer Response,NaN,Medium,Social media,2023-06-01 10:33:53,NaN,NaN,i'm having an issue with the autodesk autocad. please assist. i've noticed that the issue occurs consistently when i use a specific feature or application on my autodesk autocad.
80,81,Sarah Lee,dclark@example.net,50,Other,Microsoft Office,2021-03-22,Technical issue,Product recommendation,I'm having an issue with the {product_purchased}. Please assist. I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?,Pending Customer Response,NaN,Critical,Phone,2023-06-01 07:27:28,NaN,NaN,i'm having an issue with the microsoft office. please assist. i'm unable to find the option to perform the desired action in the microsoft office. could you please guide me through the steps?
105,106,Virginia Miller,lisahamilton@example.com,56,Other,Dyson Vacuum Cleaner,2021-07-17,Product inquiry,Battery life,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Pending Customer Response,NaN,Critical,Chat,2023-06-01 02:08:01,NaN,NaN,i'm having an issue with the dyson vacuum cleaner. please assist. i need assistance as soon as possible because it's affecting my work and productivity.
106,107,Miranda Morales,daniellebrown@example.net,42,Female,Nintendo Switch,2021-05-20,Cancellation request,Installation support,I'm having an issue with the {product_purchased}. Please assist. I've checked the device settings and made sure that everything is configured correctly.,Closed,Table admit really Mrs development move.,Low,Email,2023-06-01 11:38:01,2023-06-01 20:46:01,2.0,i'm having an issue with the nintendo switch. please assist. i've checked the device settings and made sure that everything is configured correctly.
107,108,Laura Collins,douglasmccormick@example.net,50,Other,LG Smart TV,2021-06-09,Technical issue,Account access,"I'm having an issue with the {product_purchased}. Please assist. I've checked for software updates, and my {product_purchased} is already running the latest version.",Pending Customer Response,NaN,High,Email,2023-06-01 15:49:01,NaN,NaN,"i'm having an issue with the lg smart tv. please assist. i've checked for software updates, and my lg smart tv is already running the latest version."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8386,8387,Caitlin Robinson,bsmith@example.com,24,Female,Dyson Vacuum Cleaner,2020-02-11,Refund request,Installation support,I'm having an issue with the {product_purchased}. Please assist. I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:50:37,NaN,NaN,i'm having an issue with the dyson vacuum cleaner. please assist. i'm concerned about the security of my dyson vacuum cleaner and would like to ensure that my data is safe.
8397,8398,Richard Mccarthy,xbailey@example.com,59,Female,Dell XPS,2020-07-17,Cancellation request,Cancellation request,"I'm having an issue with the {product_purchased}. Please assist. The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.",Closed,Because individual section grow.,Medium,Email,2023-06-01 06:30:51,2023-06-01 15:11:51,2.0,"i'm having an issue with the dell xps. please assist. the issue i'm facing is intermittent. sometimes it works fine, but other times it acts up unexpectedly."
8437,8438,Robert Farley,bryceshepherd@example.com,65,Female,Dyson Vacuum Cleaner,2021-11-08,Product inquiry,Peripheral compatibility,"I'm having an issue with the {product_purchased}. Please assist. I've already contacted customer support multiple times, but the issue remains unresolved.",Pending Customer Response,NaN,High,Email,2023-06-01 15:52:45,NaN,NaN,"i'm having an issue with the dyson vacuum cleaner. please assist. i've already contacted customer support multiple times, but the issue remains unresolved."
8450,8451,Joshua Gomez,hhunt@example.com,34,Other,LG Washing Machine,2021-06-16,Billing inquiry,Product setup,"I'm having an issue with the {product_purchased}. Please assist. I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.",Closed,Four professional practice let miss.,Low,Chat,2023-06-01 01:01:01,2023-06-01 18:54:01,5.0,"i'm having an issue with the lg washing machine. please assist. i've performed a factory reset on my lg washing machine, hoping it would resolve the problem, but it didn't help."
8456,8457,Jackson Strong,hannah96@example.com,18,Female,Dyson Vacuum Cleaner,2021-04-08,Product inquiry,Payment issue,"I'm having an issue with the {product_purchased}. Please assist. I've checked for any available software updates for my {product_purchased}, but there are none.",Open,NaN,Critical,Social media,NaN,NaN,NaN,"i'm having an issue with the dyson vacuum cleaner. please assist. i've checked for any available software updates for my dyson vacuum cleaner, but there are none."

In [14]:
df['Ticket Description'].nunique()

8077

In [15]:
df['Ticket Description'][0]

"I'm having an issue with the {product_purchased}. Please assist.\r\n\r\nYour billing zip code is: 71701.\r\n\r\nWe appreciate that you have requested a website address.\r\n\r\nPlease double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists."

In [16]:
df.shape

(8469, 18)

In [6]:
df_dup = df[df['Ticket_Description'].duplicated(keep=False)].copy()
df_dup['row_id'] = df_dup.index

df_dup.sort_values('Ticket_Description')

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating,Ticket_Description,row_id
7054,7055,Kyle Mcdonald,dpatton@example.org,27,Other,Amazon Echo,2020-09-13,Product inquiry,Product compatibility,"I'm having an issue with the {product_purchased}. Please assist. I've already contacted customer support multiple times, but the issue remains unresolved.",Closed,Where weight herself give rich lead.,Low,Email,2023-06-01 11:50:31,2023-06-01 14:21:31,2.0,"i'm having an issue with the amazon echo. please assist. i've already contacted customer support multiple times, but the issue remains unresolved.",7054
5679,5680,Donald Houston,kleon@example.org,45,Female,Amazon Echo,2021-12-18,Refund request,Product compatibility,"I'm having an issue with the {product_purchased}. Please assist. I've already contacted customer support multiple times, but the issue remains unresolved.",Open,NaN,Critical,Email,NaN,NaN,NaN,"i'm having an issue with the amazon echo. please assist. i've already contacted customer support multiple times, but the issue remains unresolved.",5679
871,872,Anthony Adams,lmalone@example.com,25,Male,Amazon Echo,2020-09-10,Billing inquiry,Cancellation request,I'm having an issue with the {product_purchased}. Please assist. This problem started occurring after the recent software update. I haven't made any other changes to the device.,Pending Customer Response,NaN,Low,Email,2023-06-01 12:05:37,NaN,NaN,i'm having an issue with the amazon echo. please assist. this problem started occurring after the recent software update. i haven't made any other changes to the device.,871
8168,8169,Rebecca White,matthew09@example.org,66,Male,Amazon Echo,2021-06-06,Refund request,Battery life,I'm having an issue with the {product_purchased}. Please assist. This problem started occurring after the recent software update. I haven't made any other changes to the device.,Pending Customer Response,NaN,Critical,Email,2023-06-01 13:16:39,NaN,NaN,i'm having an issue with the amazon echo. please assist. this problem started occurring after the recent software update. i haven't made any other changes to the device.,8168
2416,2417,Mackenzie Thomas,kimberlyhamilton@example.net,66,Male,Amazon Kindle,2020-01-06,Refund request,Cancellation request,I'm having an issue with the {product_purchased}. Please assist. I've noticed a peculiar error message popping up on my {product_purchased} screen. It says '{error_message}'. What does it mean?,Closed,Them general professional gun.,Medium,Chat,2023-06-01 19:28:26,2023-06-01 09:07:26,3.0,i'm having an issue with the amazon kindle. please assist. i've noticed a peculiar error message popping up on my amazon kindle screen. it says ' error message '. what does it mean?,2416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4751,4752,Stephanie Bowman,lisabradley@example.com,62,Female,Xbox,2020-05-27,Cancellation request,Refund request,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Pending Customer Response,NaN,Medium,Email,2023-06-01 05:57:49,NaN,NaN,i'm having an issue with the xbox. please assist. i need assistance as soon as possible because it's affecting my work and productivity.,4751
6115,6116,Victor Todd,nelsonroy@example.com,41,Male,Xbox,2020-09-28,Refund request,Software bug,"I'm having an issue with the {product_purchased}. Please assist. I've checked for software updates, and my {product_purchased} is already running the latest version.",Closed,Little style decade cold.,High,Phone,2023-06-01 05:10:04,2023-06-01 23:50:04,2.0,"i'm having an issue with the xbox. please assist. i've checked for software updates, and my xbox is already running the latest version.",6115
3119,3120,Aaron Abbott,meagantorres@example.com,59,Male,Xbox,2020-02-22,Technical issue,Refund request,"I'm having an issue with the {product_purchased}. Please assist. I've checked for software updates, and my {product_purchased} is already running the latest version.",Open,NaN,Medium,Chat,NaN,NaN,NaN,"i'm having an issue with the xbox. please assist. i've checked for software updates, and my xbox is already running the latest version.",3119
2060,2061,Jennifer Mcfarland,pagekaren@example.net,45,Male,Xbox,2020-07-23,Technical issue,Data loss,I'm having an issue with the {product_purchased}. Please assist. This problem started occurring after the recent software update. I haven't made any other changes to the device.,Pending Customer Response,NaN,Critical,Email,2023-06-01 21:52:07,NaN,NaN,i'm having an issue with the xbox. please assist. this problem started occurring after the recent software update. i haven't made any other changes to the device.,2060
2079,2080,Barbara Davis,sosborne@example.org,63,Male,Xbox,2021-03-05,Refund request,Peripheral compatibility,I'm having an issue with the {product_purchased}. Please assist. This problem started occurring after the recent software update. I haven't made any other changes to the device.,Pending Customer Response,NaN,Critical,Phone,2023-06-01 11:10:35,NaN,NaN,i'm having an issue with the xbox. please assist. this problem started occurring after the recent software update. i haven't made any other changes to the device.,2079

In [5]:
df['Ticket_Description'] = df.apply(cleaning_descrn, axis=1)

dup_groups = (
    df[df['Ticket_Description'].duplicated(keep=False)]
    .groupby('Ticket_Description')
    .apply(lambda x: x.index.tolist())
)

print(dup_groups)

Ticket_Description
i'm having an issue with the amazon echo. please assist. i've already contacted customer support multiple times, but the issue remains unresolved.                                       [5679, 7054]
i'm having an issue with the amazon echo. please assist. this problem started occurring after the recent software update. i haven't made any other changes to the device.                 [871, 8168]
i'm having an issue with the amazon kindle. please assist. i've noticed a peculiar error message popping up on my amazon kindle screen. it says ' error message '. what does it mean?    [2416, 6176]
i'm having an issue with the amazon kindle. please assist. the issue i'm facing is intermittent. sometimes it works fine, but other times it acts up unexpectedly.                       [3389, 5113]
i'm having an issue with the apple airpods. please assist. i rely heavily on my apple airpods for my daily tasks, and this issue is hindering my productivity.                           [4227, 4718]
                                                                                                                                                                                             ...
i'm having an issue with the sony playstation. please assist. this problem started occurring after the recent software update. i haven't made any other changes to the device.           [5186, 5451]
i'm having an issue with the sony xperia. please assist. the issue i'm facing is intermittent. sometimes it works fine, but other times it acts up unexpectedly.                         [1735, 4647]
i'm having an issue with the xbox. please assist. i need assistance as soon as possible because it's affecting my work and productivity.                                                 [3668, 4751]
i'm having an issue with the xbox. please assist. i've checked for software updates, and my xbox is already running the latest version.                                                  [3119, 6115]
i'm having an issue with the xbox. please assist. this problem started occurring after the recent software update. i haven't made any other changes to the device.                       [2060, 2079]
Length: 66, dtype: object

In [ ]:
df.head()
df['Ticket_Description'] = df.apply(cleaning_descrn, axis=1)

In [22]:
text =  df['Ticket Description']
text.duplicated().sum()

np.int64(392)

In [12]:
df['Ticket_Description'].duplicated().sum()

np.int64(74)

In [9]:
data = df['Ticket_Description'].unique()
type(data)
len(data)

8395

In [11]:
df.shape

(8469, 18)

In [17]:
data

<StringArray>
[                                                                              'i'm having an issue with the gopro hero. please assist. your billing zip code is: 71701. we appreciate that you have requested a website address. please double check your email address. i've tried troubleshooting steps mentioned in the user manual, but the issue persists.',
                                                                                        'i'm having an issue with the lg smart tv. please assist. if you need to change an existing product. i'm having an issue with the lg smart tv. please assist. if the issue i'm facing is intermittent. sometimes it works fine, but other times it acts up unexpectedly.',
                                                                                                              'i'm facing a problem with my dell xps. the dell xps is not turning on. it was working fine until yesterday, but now it doesn't respond. 1.8.3 i really i'm using the original charger that came with my dell xps, but it's not charging properly.',
                                                                                             'i'm having an issue with the microsoft office. please assist. if you have a problem you're interested in and i'd love to see this happen, please check out the feedback. i've already contacted customer support multiple times, but the issue remains unresolved.',
                          'i'm having an issue with the autodesk autocad. please assist. note: the seller is not responsible for any damages arising out of the delivery of the battleground game. please have the game in good condition and shipped to you i've noticed a sudden decrease in battery life on my autodesk autocad. it used to last much longer.',
                                                                                                                                                'i'm facing a problem with my microsoft office. the microsoft office is not turning on. it was working fine until yesterday, but now it doesn't respond. to remove the new microsoft office, but there are none.',
               'i'm unable to access my microsoft surface account. it keeps displaying an 'invalid credentials' error, even though i'm using the correct login information. how can i regain access to my account? solution 1 i'm unable to find the option to perform the desired action in the microsoft surface. could you please guide me through the steps?',
                        'i'm having an issue with the philips hue lights. please assist. (thanks) i will contact all my suppliers and confirm. please try and find out whether their inventory is currently stocked, or any other reason. i am i've performed a factory reset on my philips hue lights, hoping it would resolve the problem, but it didn't help.',
 'i'm having an issue with the fitbit versa smartwatch. please assist. thank you. fitbit versa smartwatch is not the exact type you might prefer, they use the exact same method for different uses. please help i've recently updated the firmware of my fitbit versa smartwatch, and the issue started happening afterward. could it be related to the update?',
                                                  'my dyson vacuum cleaner is making strange noises and not functioning properly. i suspect there might be a hardware issue. can you please help me with this? if we can, please send a "request" to dav the issue i'm facing is intermittent. sometimes it works fine, but other times it acts up unexpectedly.',
 ...
                                                                               'i'm having an issue with the canon dslr camera. please assist. if you can't help, please call in a few hrs before purchasing. maritime ipsos.blogspot.com - 1,092 pages - november i've followed the troubleshooting steps mentioned in the user manual, but the issue persists.',
                        'i've accidentally deleted important data from my apple airpods. is there any way to recover the deleted files? i need them urgently. your name should also be included in the account list. i did not have any data or this problem started occurring after the recent software update. i haven't made any other changes to the device.',
                                                     'i'm having an issue with the microsoft office. please assist. how can i get help from g&h?? we look for help in many ways. we work diligently to answer customer question. we also follow this problem started occurring after the recent software update. i haven't made any other changes to the device.',
                                                                        'i'm having an issue with the samsung soundbar. please assist. you were able to purchase the product at the store. please report any problems you can. sorry, there are no items for purchase. i've already contacted customer support multiple times, but the issue remains unresolved.',
                                                       'there seems to be a glitch in the lg washing machine software. it freezes frequently, making it difficult to use. can you please provide a solution? it seemed that they tried to solve this in an earlier post 1 i need assistance as soon as possible because it's affecting my work and productivity.',
                                                                       'my lg oled is making strange noises and not functioning properly. i suspect there might be a hardware issue. can you please help me with this? as always, you can email me at support@laserprint. i need assistance as soon as possible because it's affecting my work and productivity.',
                                                                                                   'i'm having an issue with the bose soundlink speaker. please assist. sell for 30-35% (i also bought a 2.5mm and i'm getting stuck). buy for 80-100% ( the issue i'm facing is intermittent. sometimes it works fine, but other times it acts up unexpectedly.',
                                                                                                                  'i'm having an issue with the gopro action camera. please assist. you are using a different browser than the one i'm using. i've performed a factory reset on my gopro action camera, hoping it would resolve the problem, but it didn't help.',
                                                              'i'm having an issue with the playstation. please assist. i don't think a product is in the same category as an playstation, as it wouldn't have been the issue in the case of the i've noticed that the issue occurs consistently when i use a specific feature or application on my playstation.',
                                                             'there seems to be a hardware problem with my philips hue lights. the screen is flickering, and i'm unable to use it. what should i do? i'll try my best to fix it now. i could get a i've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.']
Length: 8395, dtype: str

In [18]:
import nltk 

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Saranya\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Saranya\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Saranya\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [21]:
data

<StringArray>
[                                                                              'i'm having an issue with the gopro hero. please assist. your billing zip code is: 71701. we appreciate that you have requested a website address. please double check your email address. i've tried troubleshooting steps mentioned in the user manual, but the issue persists.',
                                                                                        'i'm having an issue with the lg smart tv. please assist. if you need to change an existing product. i'm having an issue with the lg smart tv. please assist. if the issue i'm facing is intermittent. sometimes it works fine, but other times it acts up unexpectedly.',
                                                                                                              'i'm facing a problem with my dell xps. the dell xps is not turning on. it was working fine until yesterday, but now it doesn't respond. 1.8.3 i really i'm using the original charger that came with my dell xps, but it's not charging properly.',
                                                                                             'i'm having an issue with the microsoft office. please assist. if you have a problem you're interested in and i'd love to see this happen, please check out the feedback. i've already contacted customer support multiple times, but the issue remains unresolved.',
                          'i'm having an issue with the autodesk autocad. please assist. note: the seller is not responsible for any damages arising out of the delivery of the battleground game. please have the game in good condition and shipped to you i've noticed a sudden decrease in battery life on my autodesk autocad. it used to last much longer.',
                                                                                                                                                'i'm facing a problem with my microsoft office. the microsoft office is not turning on. it was working fine until yesterday, but now it doesn't respond. to remove the new microsoft office, but there are none.',
               'i'm unable to access my microsoft surface account. it keeps displaying an 'invalid credentials' error, even though i'm using the correct login information. how can i regain access to my account? solution 1 i'm unable to find the option to perform the desired action in the microsoft surface. could you please guide me through the steps?',
                        'i'm having an issue with the philips hue lights. please assist. (thanks) i will contact all my suppliers and confirm. please try and find out whether their inventory is currently stocked, or any other reason. i am i've performed a factory reset on my philips hue lights, hoping it would resolve the problem, but it didn't help.',
 'i'm having an issue with the fitbit versa smartwatch. please assist. thank you. fitbit versa smartwatch is not the exact type you might prefer, they use the exact same method for different uses. please help i've recently updated the firmware of my fitbit versa smartwatch, and the issue started happening afterward. could it be related to the update?',
                                                  'my dyson vacuum cleaner is making strange noises and not functioning properly. i suspect there might be a hardware issue. can you please help me with this? if we can, please send a "request" to dav the issue i'm facing is intermittent. sometimes it works fine, but other times it acts up unexpectedly.',
 ...
                                                                               'i'm having an issue with the canon dslr camera. please assist. if you can't help, please call in a few hrs before purchasing. maritime ipsos.blogspot.com - 1,092 pages - november i've followed the troubleshooting steps mentioned in the user manual, but the issue persists.',
                        'i've accidentally deleted important data from my apple airpods. is there any way to recover the deleted files? i need them urgently. your name should also be included in the account list. i did not have any data or this problem started occurring after the recent software update. i haven't made any other changes to the device.',
                                                     'i'm having an issue with the microsoft office. please assist. how can i get help from g&h?? we look for help in many ways. we work diligently to answer customer question. we also follow this problem started occurring after the recent software update. i haven't made any other changes to the device.',
                                                                        'i'm having an issue with the samsung soundbar. please assist. you were able to purchase the product at the store. please report any problems you can. sorry, there are no items for purchase. i've already contacted customer support multiple times, but the issue remains unresolved.',
                                                       'there seems to be a glitch in the lg washing machine software. it freezes frequently, making it difficult to use. can you please provide a solution? it seemed that they tried to solve this in an earlier post 1 i need assistance as soon as possible because it's affecting my work and productivity.',
                                                                       'my lg oled is making strange noises and not functioning properly. i suspect there might be a hardware issue. can you please help me with this? as always, you can email me at support@laserprint. i need assistance as soon as possible because it's affecting my work and productivity.',
                                                                                                   'i'm having an issue with the bose soundlink speaker. please assist. sell for 30-35% (i also bought a 2.5mm and i'm getting stuck). buy for 80-100% ( the issue i'm facing is intermittent. sometimes it works fine, but other times it acts up unexpectedly.',
                                                                                                                  'i'm having an issue with the gopro action camera. please assist. you are using a different browser than the one i'm using. i've performed a factory reset on my gopro action camera, hoping it would resolve the problem, but it didn't help.',
                                                              'i'm having an issue with the playstation. please assist. i don't think a product is in the same category as an playstation, as it wouldn't have been the issue in the case of the i've noticed that the issue occurs consistently when i use a specific feature or application on my playstation.',
                                                             'there seems to be a hardware problem with my philips hue lights. the screen is flickering, and i'm unable to use it. what should i do? i'll try my best to fix it now. i could get a i've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.']
Length: 8395, dtype: str

In [27]:
lemmatizer = nltk.WordNetLemmatizer()

preprocessed_data = []
for sent in data:
    tokens = nltk.word_tokenize(sent)
    temp = ""
    for token in tokens:
        if re.search(r'[^a-zA-Z0-9]', token):
            print(token)
        else:
            temp = ' '.join([temp, lemmatizer.lemmatize(lemmatizer.lemmatize(token, pos='v'), pos = 'n')])

    preprocessed_data.append(temp)

'm
.
.
:
71701.
.
.
've
,
.
'm
.
.
.
'm
.
.
'm
.
,
.
'm
.
.
,
n't
.
1.8.3
'm
,
's
.
'm
.
.
're
'd
,
.
've
,
.
'm
.
.
:
.
've
.
.
'm
.
.
,
n't
.
,
.
'm
.
'invalid
'
,
'm
.
?
'm
.
?
'm
.
.
(
)
.
,
.
've
,
,
n't
.
'm
.
.
.
,
.
've
,
.
?
.
.
?
,
``
''
'm
.
,
.
'm
.
.
1-800-799-0808.
:
's
2-3-4-5
?
'm
,
's
.
'm
.
.
4.
mr.
.
5.
've
,
n't
.
'm
.
.
:
n't
?
.
:
's
've
.
've
.
've
,
.
?
n't
'product
'
'm
.
'm
.
.
:
:
:
11,532
:
've
,
.
?
'm
.
.
,
,
've
.
.
'm
.
.
-
:
.
,
'm
.
'm
.
.
!
''
*
-
-
-
've
,
n't
.
'm
.
.
...
'm
.
,
.
'm
.
.
'm
.
.
:
've
,
.
'm
.
assist.
``
-name
``
pro.
``
``
-version
1.10.2
``
1.10.2
''
``
-usage
've
,
.
'm
.
.
:
@
julietr.com
,
.
've
,
.
'm
.
.
(
,
.
)
1.3.2.1
3.0
.
'm
.
,
.
'm
.
.
'll
.
've
,
,
n't
.
'm
.
.
.
,
've
.
.
.
.
?
,
.
'm
,
.
'm
.
,
.
?
,
.
've
,
,
n't
.
'm
.
.
.
'm
.
,
.
'm
.
.
.
''
.
``
'm
,
's
.
'm
.
.
's
.
've
,
.
'm
.
.
'm
.
.
've
.
?
've
.
'm
.
.
$
29.89
.
,
've
,
.
've
.
's
.
?
's
.
'm
.
.
:
``
-
,
,
'm
.
'm
.
.
3-3
,
,
.
.
3-2
've
,
.
?
've
,
.
?
,
.
've
.
.
'm
.
.
,
,
's
n't
.
,
've
,
.
've
,
.
?
:
:
've
,
.
?
'm
.
.
1.
?
,
's
'm
.
?
'm
.
.
.
'm
:
system.collectedmessage.throwback
'm
.
've
,
.
?
've
.
'm
.
.
,
n't
.
'd
'm
.
,
.
'm
.
.
's
.
's
.
'm
.
.
.
''
(
)
:
``
've
,
.
?
'm
.
.
,
,
:
``
'm
.
?
'm
.
.
''
.
``
'm
1.0
.
.
''
``
'm
'm
.
'm
.
.
.
,
.
's
.
'm
.
.
,
,
.
?
'm
,
.
'm
.
.
.
n't
.
n't
?
.
'm
.
?
'm
.
.
've
,
.
,
303.938.2837.
'm
'm
.
'm
.
,
.
?
.
'm
,
.
've
,
.
?
.......................................................
.
:
//forum.ejconop
've
,
n't
.
'm
.
.
.
.
's
.
'm
.
.
's
n't
.
've
,
,
n't
.
've
.
's
.
?
u.s.
,
.
?
'm
.
.
–
.
.
(
'm
.
?
'm
.
.
've
.
'm
.
.
!
's
's
.
,
.
've
,
.
've
,
.
?
?
'm
.
,
.
'm
.
.
:
've
.
'm
.
'm
.
.
's
'm
.
.
's
've
,
,
n't
.
'm
.
.
$
,
've
,
.
'm
.
.
(
)
(
(
$
)
//
'm
.
,
.
'm
.
.
4.1.7
.
.
'll
(
've
.
'm
.
.
,
n't
.
'm
've
.
'
'
.
?
.
,
.
?
``
'd
.
's
've
.
'
'
.
?
've
.
's
.
?
'm
.
,
.
've
.
?
.
?
.
'm
hardware-related
.
'm
.
.
,
.
)
've
,
,
n't
.
'm
.
'invalid
'
,
'm
.
?
n't
'm
.
've
.
?
.
?
'm
,
's
.
've
,
.
?
've
,
.
'm
.
.
.
've
,
've
,
.
.
.
?
.
've
.
'
'
.
?
'm
.
.
,
.
m.v.v
.
above-mentioned
've
.
'm
.
.
1.
,
,
've
,
.
'm
.
.
've
$
!
.
'm
,
.
'm
.
.
4-8-0-1
.
:
've
.
'm
.
.
's
,
n't
've
,
,
n't
.
'm
.
.
n't
.
've
,
,
,
.
'm
.
.
'm
.
?
'm
.
,
.
?
n't
.
's
'm
.
?
'm
.
.
.
've
,
.
'm
.
.
.
.
've
.
.
'm
.
.
?
.
'm
,
.
've
,
.
?
,
've
,
n't
.
'm
.
.
*
*
*
@
.
'm
.
.
,
n't
.
'm
,
'm
.
?
'm
d.
.
|
-
-
|
|
've
,
n't
.
'm
.
.
,
.
.
've
,
.
've
,
.
?
-
'm
.
,
.
'm
.
.
(
,
.
n't
.
'm
.
.
:
``
''
.
've
.
.
'm
.
.
in-app
n't
.
in-app
.
've
.
'
'
.
?
'm
.
.
:
//www.kyle
@
junebug.com/tutorial/cure-all-
've
,
.
,
.
?
?
've
.
'
'
.
?
'm
.
.
,
n't
.
'm
.
'm
.
've
,
.
?
:
've
,
n't
.
'm
.
.
,
.
.
've
,
.
?
'm
.
.
.
've
.
'
'
.
?
'm
.
.
'm
.
,
.
've
,
.
'm
.
.
,
:
'no
.
'
,
'user-
,
.
've
.
?
.
.
(
'm
've
,
.
'm
.
.
,
.
've
.
'm
.
,
.
?
?
've
,
.
'm
.
.
's
.
'm
.
.
've
.
'm
.
.
've
,
.
'm
.
assist.
``
,
``
:
//api.blockchain.info/api/v1/v1.0
``
;
,
've
.
.
.
.
?
:
:
//mycli.org/
.
've
.
'
'
.
?
've
.
?
.
.
'm
.
've
.
'
'
.
?
'm
.
.
,
.
.
's
.
'm
.
.
.
un-useful
,
.
've
.
.
'm
.
.
'm
've
,
,
,
.
.
.
?
.
:
've
.
'm
.
.
,
.
.
've
,
.
'm
.
.
!
've
,
.
,
.
?
.
've
,
,
n't
.
'm
.
.
)
.
.
)
pavilion.please
.
've
,
.
'm
.
.
5.2.2.5
(
'm
.
.
'm
.
,
.
'm
.
.
's
,
.
!
,
've
,
.
'm
.
.
-
,
:
-
display/filter
-
-
've
,
,
n't
.
've
.
's
.
?
,
'm
.
'm
.
.
*
12.09.2017
,
:
*
*
*
've
,
,
n't
.
'm
.
.
-d
-d
-c
-s
//
've
,
.
'm
.
.
,
,
,
,
.
've
,
.
'm
.
.
:
//www.wizards.com/en-us/product/world/the-oblivion.pau/product
've
,
.
'm
.
.
1.
.
2.
,
,
'm
.
,
.
'm
.
.
4.3.0
*
4.2.2
*
've
.
'm
.
.
non-issue
.
'll
.
again.bdn
's
:
'm
,
's
.
'm
.
.
.
've
,
.
'm
.
.
'm
.
assist.
``
:
've
,
.
?
.
,
'm
.
?
n't
,
's
's
's
.
'm
.
.
,
'm
.
've
.
.
'm
.
.
.
'm
.
.
.
'm
've
,
.
?
've
.
.
?
n't
,
?
've
,
,
n't
.
'm
.
.
:
$
33.00
'm
.
?
'm
.
.
<
type=
''
''
've
,
.
'm
.
.
'll
2-3
.
.
've
,
.
'm
.
.
10:44:17
's
:
.
.
'm
,
's
.
.
,
'm
.
?
'm
,
n't
've
,
.
?
'm
.
.
(
)
.
've
,
.
?
'm
.
.
're
'm
hardware-related
.
'm
.
.
.
'm
,
's
.
'm
.
.
.
've
,
,
n't
.
'm
.
.
,
.
(
,
're
,
've
,
.
'm
.
.
,
.
,
'm
,
.
'm
.
.
,
.
.
''
'm
hardware-related
.
'm
.
.
:
:
:
:
:
:
a-z
.
.
.
n't
.
'm
.
.
:
//support.android.com/en-us/htm-htm.4.0-a0.apk
've
.
'
'
.
?
'm
.
.
're
!
's
...
'm
.
?
'm
.
.
:
're
,
.
.
've
.
'm
.
.
,
.
.
.
n't
.
'm
.
.
:
.
:
.
:
``
''
:
,
.
'm
.
.
6.0.2
.
6.0.1
.
6.0.0
've
,
.
'm
.
.
.
.
:
've
,
.
'm
.
.
:
)
(
1.1.4.29
)
:
:
//forum.xbox.com/xbox-server/show
'm
.
'm
.
.
``
.
'll
've
,
,
n't
.
'm
.
.
.
.
've
,
.
.
,
'm
.
?
's
.
'm
.
.
?
.
'll
.
've
,
n't
.
'm
.
.
:
,
``
''
.
,
's
.
n't
.
'm
.
.
,
.
?
'm
.
.
,
n't
.
,
.
'm
.
?
'm
.
.
'm
.
.
'm
.
.
n't
.
've
,
.
?
've
.
.
'm
.
.
,
$
3.99
-
$
3.98
,
%
've
.
'
'
.
?
've
,
.
?
?
,
've
,
.
've
.
's
.
?
.
)
'm
.
'm
.
.
e-mail
,
.
,
,
'm
.
'm
.
.
,
'm
(
'm
.
'm
.
.
's
.
's
,
've
,
.
'm
.
.
's
.
've
,
.
?
'm
.
.
.
.
.
've
,
.
.
.
?
've
,
.
'm
.
.
01:12:47.547
thread/info
:
've
,
.
'm
.
.
-
,
``
''
-
,
-
(
,
)
(
's
.
'm
.
.
,
'm
,
.
'm
.
.
$
5.00
.
.
$
13.00
.
.
've
,
.
,
.
?
.
's
.
'm
.
.
,
n't
.
?
've
,
.
'm
.
.
'm
.
.
m-100
'm
've
.
'm
.
.
.
n't
.
.
'm
.
've
,
.
'm
.
.
?
.
,
'm
.
'm
.
.
1.
%
.
2.
%
.
3.
,
.
.
,
.
?
a.
,
'm
.
'm
wi-fi
.
n't
,
.
?
've
,
n't
.
'm
.
.
.
.
n't
.
've
,
,
'm
.
.
,
'm
.
?
n't
've
.
.
'm
.
.
.
've
,
,
n't
.
'm
.
.
.
:
've
,
.
.
.
?
'frequently
'
've
,
.
'm
.
.
17:42
a2d3-x-xx
:
c-15-x-xx-xx
'm
.
,
.
've
.
's
.
?
1.
.
'm
.
?
'm
.
.
(
'm
'
'
'id
'
)
.
've
,
.
've
,
.
?
've
,
.
'm
.
.
—
—
—
.
'm
,
.
've
.
's
.
?
've
,
.
'm
.
.
*
.
*
,
'm
hardware-related
.
'm
.
.
3.6
vendor-specific
<
've
,
.
?
'm
.
.
/
a/s
:
:
'm
.
'm
.
.
-
(
e.g
.
,
,
)
-
'm
.
,
.
'm
.
.
@
crowdfunding.com
.
!
've
.
'
'
.
?
'm
.
.
.
'll
,
.
've
,
n't
.
'm
.
.
,
.
.
'm
.
'm
.
.
,
.
'll
.
'm
.
?
'm
.
.
.
n't
(
,
,
)
.
've
.
'm
.
.
've
,
n't
.
'm
.
.
.
$
n't
,
'd
.
'm
.
'm
.
'invalid
'
,
'm
.
?
•
'm
.
,
.
'm
.
.
.
$
$
$
...
pic.twitter.com/rqdp
'm
.
'm
.
.
's
've
:
:
//www.mobilegrouper
.
've
,
.
'm
.
.
're
,
.
.
've
,
.
?
'm
.
.
'm
.
.
,
,
.
'm
.
.
,
n't
.
$
-s
've
.
'
'
.
?
've
.
?
.
.
'm
.
'm
.
,
.
?
,
've
,
.
'm
.
.
's
's
.
n't
.
'm
.
.
$
.
'm
.
'm
.
.
!
.
opt-out
.
re-
'm
.
?
'm
.
.
(
)
.
'm
.
?
'm
.
.
.
'm
.
.
.
'm
'm
.
?
'm
.
.
,
n't
.
,
's
've
.
'm
.
assist.
``
=
'
1.13191422152955456214954559.454545.45453057.4545
've
,
.
'm
.
.
'm
,
.
'm
.
.
.
'm
.
,
.
'm
.
.
'm
/
've
,
.
.
,
'm
.
?
.
've
,
.
'm
.
.
``
''
,
''
.
've
.
'm
.
.
!
.
``
''
.
've
,
.
?
'm
.
.
!
's
,
$
,
$
3,600
pre-order
,
.
'm
.
.
.
've
,
,
n't
.
'm
.
.
'm
(
)
.
.
'm
.
,
.
'm
.
.
!
've
,
.
?
'm
.
.
.
,
,
'm
,
.
'm
.
.
's
;
n't
.
?
'm
.
?
've
,
.
?
.
've
.
'
'
.
?
'm
.
.
're
.
've
,
.
'm
.
.
,
.
've
.
've
,
.
'm
.
.
'add
'
,
:
'sorry
–
.
'm
,
's
.
'm
.
.
(
)
.
've
,
.
?
'm
.
.
)
,
.
)
.
n't
.
'm
.
.
,
,
&
.
.
'm
hardware-related
.
'm
.
'invalid
'
,
'm
.
?
've
,
.
'm
.
.
,
,
.
've
,
.
'm
.
.
.
,
've
.
've
'm
,
's
.
'm
.
.
.
.
!
3/28
'm
.
,
.
've
.
?
.
—
j.
(
@
)
,
'm
.
,
.
'm
.
.
!
,
,
's
.
'm
wi-fi
.
n't
,
.
?
've
'm
.
?
'm
.
.
'm
,
.
'm
.
.
.
(
n't
)
.
've
.
'
'
.
?
've
.
's
.
?
've
's
.
'm
,
's
.
'm
.
,
.
?
'm
.
,
.
'm
.
.
,
n't
.
``
've
,
.
'm
.
.
,
.
:
've
,
.
?
'm
.
.
'll
.
.
''
``
''
?
's
.
'm
.
.
've
,
.
'm
.
assist.
``
(
)
(
)
(
)
(
)
``
'm
,
's
.
'm
.
.
n't
,
'll
's
,
've
,
,
n't
.
'm
.
.
-
,
,
``
``
!
!
've
,
,
n't
.
'm
wi-fi
.
n't
,
.
?
:
've
,
.
'm
.
.
'm
.
.
.
're
,
.
n't
.
'm
.
.
,
,
.
1-day
:
$
4.99
'm
.
?
'm
.
'invalid
'
,
'm
.
?
've
,
.
'm
.
.
$
:
$
:
$
:
$
:
$
1,000
:
$
2,000
:
$
3,000
:
$
4,000
:
$
've
,
,
n't
.
'm
.
.
.
``
've
,
,
,
.
'm
.
.
'm
.
'm
.
.
've
,
n't
.
'm
.
.
n't
.
,
!
.
.
:
've
,
.
've
,
.
?
:
've
.
'm
.
'invalid
'
,
'm
.
?
'm
.
,
.
'm
.
.
?
.
,
.
've
.
'
'
.
?
'm
.
.
've
.
'
'
.
?
've
,
.
?
've
,
,
n't
.
'm
.
.
.
's
,
.
'm
'm
.
?
've
,
.
?
,
,
've
.
'
'
.
?
'm
.
.
,
.
'm
hardware-related
.
'm
.
.
,
:
@
tacom.com
.
,
'm
.
,
.
'm
.
.
n't
's
,
n't
've
,
.
'm
.
.
,
.
ad-hoc
've
,
,
n't
.
'm
.
.
.
.
've
,
.
'm
.
.
-
,
.
've
.
.
'm
.
'invalid
'
,
'm
.
?
.
've
.
.
'm
.
assist.
``
>
>
:
.
(
=='\r
'
've
,
.
?
'm
.
.
,
,
''
.
``
.
'll
,
!
.
n't
.
've
.
's
.
?
've
,
.
'm
.
.
've
.
'm
.
.
.
,
.
'm
.
.
n't
.
'm
.
.
<
'm
.
'm
.
.
've
,
,
,
.
'm
.
.
's
.
.
.
?
've
,
.
'm
.
.
:
.
.
've
,
.
'm
.
.
'm
.
.
'm
.
'
'
.
?
've
.
.
?
.
've
,
.
'm
.
.
.
n't
.
'm
.
.
,
.
'm
.
.
!
''
,
?
``
'm
's
.
'm
.
.
.
'm
.
,
.
.
.
?
,
.
'm
.
.
(
n't
)
.
.
'm
.
,
.
'm
.
.
,
;
,
're
'll
've
.
'
'
.
?
'm
.
.
:
.
:
,
,
n't
.
've
,
.
?
've
,
.
'm
.
.
.
.
n't
.
'm
.
.
*
*
,
.
*
.
*
*
've
,
.
'm
.
.
've
,
n't
.
'm
.
.
.
've
.
'
'
.
?
'm
.
.
!
.
've
.
'
'
.
?
'm
.
.
?
:
:
8x10mm/
'm
,
's
.
'm
.
.
's
.
've
.
'm
.
.
'm
:
--
.
've
,
.
?
.
,
.
?
've
'buy
'
'buy
've
,
,
n't
.
'm
.
.
,
.
.
've
.
'm
.
.
've
,
.
?
'm
.
.
-
void.io
d3.net.ai
dino.co.uk
dnb.co.uk
've
,
.
?
'm
.
.
-
on-line
.
-
'm
.
'm
.
.
,
,
,
.
'm
.
?
've
.
.
?
.
's
've
,
.
'm
.
.
.
.
've
,
.
'm
.
.
,
n't
.
's
.
'm
.
.
*
/
(
)
;
(
!
(
)
)
(
've
,
.
'm
.
.
=
>
.
'
'
.
?
'm
.
.
,
``
:
''
,
've
.
'm
.
.
've
,
,
,
.
've
,
.
?
.
've
,
.
?
'm
.
.
'm
.
.
'm
?
's
.
've
,
.
?
've
,
.
'm
.
.
.
.
,
'm
.
?
'm
.
.
.
.
.
ups/payment
:
,
've
.
'
'
.
?
'm
.
.
<
!
--
//
//
//
//
<
/
'm
.
'm
.
.
*
.
's
.
'm
.
?
'm
.
.
$
1,000
.
's
.
've
,
.
.
,
'm
.
?
:
've
,
.
.
.
?
-
-
.
-
've
,
.
'm
.
.
.
.
've
,
.
'm
.
.
,
.
,
'm
,
.
,
.
?
--
10/3/2015
6:55:33
've
.
.
've
.
.
?
!
''
a.
've
,
.
've
,
.
?
've
.
.
'm
.
.
.
've
,
.
?
'm
.
.
've
,
,
n't
.
'm
.
.
(
,
.
.
've
,
.
'm
wi-fi
.
n't
,
.
?
's
'm
.
,
.
'm
.
.
's
.
'll
.
'm
.
?
'm
.
.
'll
.
?
's
:
'm
.
,
.
'm
.
.
's
.
'm
.
.
'll
.
'd
!
'm
.
?
'm
.
,
.
?
.
n't
.
'm
.
.
•
.
•
.
n't
.
'm
.
.
're
.
.
'm
.
?
've
.
.
?
.
n't
.
've
,
n't
.
've
.
's
.
?
-
've
.
'm
.
.
—
,
've
,
,
n't
.
'm
.
.
:
·
3.6
·
·
've
,
.
?
,
.
?
.
?
'm
.
?
've
.
?
.
.
've
,
.
.
.
?
,
've
,
.
'm
.
.
,
.
,
,
's
.
'm
.
.
.
,
,
's
.
'm
.
.
,
@
samsung.com
.
'm
.
,
.
'm
.
.
?
$
n't
.
n't
've
,
.
'm
.
.
``
''
,
're
.
,
.
'm
,
.
'm
.
.
,
n't
.
?
'm
've
,
.
'm
.
.
've
,
n't
.
'm
.
.
n't
:
(
)
!
(
've
.
'm
.
.
,
?
``
.
'm
,
.
'm
.
.
.
.
.
.
've
.
'
'
.
?
'm
.
.
$
300.00
've
.
've
.
?
.
.
've
,
,
,
.
'm
.
.
.
'm
.
'm
.
.
$
.
.
1:30pm
,
.
'm
.
.
!
*
@
*
@
've
,
.
.
,
'm
.
?
's
.
've
,
.
'm
.
.
.
n't
,
.
.
've
.
.
'm
.
,
.
?
?
've
.
'
'
.
?
'm
.
.
.
.
'm
.
?
'm
.
.
's
.
's
.
'm
.
.
's
(
've
,
.
.
.
?
:
:
've
.
'm
.
.
'm
.
.
'm
,
.
've
.
?
.
,
.
'm
.
.
*
/
(
,
,
)
:
self.product
=
(
.
've
.
.
'm
.
.
.
``
``
,
.
'm
.
.
.
4.1
(
)
.
,
.
'm
.
.
•
'm
,
's
.
'm
d.
.
24/12/2014
,
11:22:41
:
!
24/12/2014
've
,
.
'm
.
.
0/4
-
0.1
(
0.00
%
)
1.0
(
0.00
%
)
've
,
,
,
.
'm
.
.
3.
.
4.
.
'm
.
?
'm
.
.
,
.
've
,
.
?
've
.
.
?
've
.
'm
.
.
.
,
.
've
.
.
'm
.
.
've
4.
'll
(
,
.
.
.
?
...
've
,
,
n't
.
'm
.
.
's
.
,
.
'm
.
,
.
'm
.
.
'll
,
.
've
,
.
'm
.
.
$
$
1.25
!
(
)
*
$
,
$
.
(
've
,
,
n't
.
've
.
?
.
.
``
'm
.
'm
.
.
,
.
.
)
,
've
,
.
.
.
?
:
'm
.
?
've
.
?
.
've
.
've
,
,
n't
.
.
.
?
:
've
,
.
'm
.
.
.
're
$
,
$
,
$
.
're
$
2,867
,
.
n't
.
'm
.
.
:
n't
?
.
n't
.
.
,
'm
.
?
.
,
.
'm
.
.
18:59:16
:
*
*
/
(
(
)
)
:
(
)
<
/b
'm
,
.
'm
.
.
-
↑
:
:
//thenewworldorderarchive.com/
've
,
,
n't
.
,
.
?
,
'd
've
.
.
,
.
?
'm
.
n't
,
,
've
.
'm
.
.
.
%
.
.
'm
.
,
.
'm
.
.
,
'll
n't
.
.
.
'm
,
.
'm
.
.
've
,
.
.
.
?
.
!
've
,
.
'm
.
.
*
@
*
*
.
*
>
*
troubleshooting/
'm
.
,
.
'm
.
.
've
,
,
n't
.
've
,
.
?
've
.
.
'm
.
.
!
!
!
.
,
.
,
.
'm
.
.
's
n't
,
.
.
've
,
.
'm
.
.
?
•
.
's
.
'm
.
.
:
//github.com/totem/totem-tetris-free
2.5.5
:
've
,
.
'm
.
.
.
10/31/2016
19:16:14
10/31/2016
19:16:17
n/a
've
,
.
'm
.
.
—
r.
(
@
)
,
,
.
'm
.
,
.
'm
.
.
.
.
've
,
.
'm
.
.
,
.
.
'm
.
?
've
.
?
.
re-download
's
.
've
.
.
?
'm
,
.
'm
.
.
``
.
.
n't
.
'm
.
.
,
@
gemini.com
g.f.s
.
2-3
'm
.
'm
.
.
.
.
,
.
'm
.
.
'm
,
.
,
?
,
'm
,
's
.
.
.
?
.
'
'
.
?
'm
.
.
,
n't
.
.
n't
.
'm
.
'invalid
'
,
'm
.
?
've
,
,
,
.
'm
.
.
``
n't
.
''
one-time
$
11,000
've
,
.
'm
wi-fi
.
n't
,
.
?
'm
.
?
'm
wi-fi
.
n't
,
.
?
'm
.
?
'm
.
.
's
.
n't
.
'm
.
?
've
,
.
?
,
've
,
,
n't
.
'm
.
.
.
's
.
've
,
.
'm
.
.
$
1,199.00
id:1
,
've
,
n't
.
'm
.
.
.
'm
.
'm
.
'invalid
'
,
'm
.
?
'm
,
.
'm
.
.
--
--
--
--
--
--
--
--
--
--
--
--
--
--
...
:
<
:
//lists.linuxfoundation.org/pipermail/linux-foundation-
've
,
.
'm
.
.
,
've
.
.
'm
.
.
...
coffee/soda
'm
.
?
.
.
?
:
:
//cse.cc/fcs/
've
,
.
've
.
's
.
?
's
'm
.
'm
.
.
,
,
!
've
,
.
.
,
.
?
!
've
,
.
?
.
,
.
?
'm
'm
.
'm
.
.
//
(
,
)
$
'm
hardware-related
.
'm
d.
.
...
2.99
.
$
...
.
've
,
.
'm
.
.
'm
.
,
//
.
,
's
.
'm
.
.
's
,
.
'm
.
'm
.
.
'm
.
'm
.
.
<
iid=2b6a7c1a9-a2cc-4f39-9fb7-d4b49d7da
've
.
'm
.
,
.
?
'll
.
've
,
.
'm
.
.
.
.
.
.
.
//
've
,
.
?
'm
.
.
'm
,
's
.
.
n't
've
,
n't
.
'm
.
.
,
.
'm
's
've
,
.
'm
.
.
4.
.
purchase.com
'm
.
'm
.
.
:
)
:
//gist.github.com/12371312/9b9ba40a2c7e7d35fd47c0d
've
,
.
'm
.
.
n't
.
's
.
'm
.
.
.
.
'm
.
,
.
'm
.
.
.
:
-
've
.
'
'
.
?
'm
.
,
.
?
(
,
)
've
.
'
'
.
?
'm
.
.
:
//www.shiftinggear.com/product/dv/
1.0.8
-
've
,
.
'm
.
.
$
0.50
$
7.99
.
n't
.
,
.
'm
.
.
.
.
've
.
've
.
's
.
?
's
've
.
've
,
.
?
'm
.
?
'm
.
.
*
/
<
=
``
''
=
``
5c0f4c7e2-845f-
've
,
,
n't
.
'm
.
.
(
)
.
(
)
've
,
.
'm
.
.
non-refundable
,
.
.
'm
hardware-related
.
'm
.
.
've
,
.
'm
.
.
.
.
|
|
|
|
've
,
.
'm
.
.
3/1/16
.
``
''
.
n't
.
'm
.
.
(
'm
.
)
'm
.
'm
.
.
``
!
.
n't
$
've
.
'm
.
.
've
.
.
.
?
've
,
.
?
.
.
?
,
.
'm
hardware-related
.
'm
.
.
=
document.getelementbyid
(
'product
'
)
;
(
!
productid.length
)
've
,
.
've
.
?
.
12:43:40
'm
.
,
.
'm
.
.
?
's
,
've
,
.
'm
.
,
.
?
've
,
.
'm
.
.
,
.
,
've
,
,
n't
.
.
.
?
,
o'neil
've
,
,
n't
.
'm
.
assist.
``
``
(
,
)
've
.
.
'm
.
.
*
's
.
*
fisheries.com
'm
.
,
.
'm
.
.
!
.
7.3.1
,
've
.
'
'
.
?
'm
.
.
?
,
n't
've
,
,
n't
.
'm
.
.
:
:
d3-m3
:
:
:
'm
,
.
'm
.
.
'm
.
.
.
'm
.
.
,
'm
.
?
,
'm
.
?
've
,
.
?
,
's
.
've
,
.
'm
d.
.
,
@
cadetv.net
.
.
've
,
.
'm
d.
.
27/12/2014
,
5:02:00
:
,
.
'm
.
.
,
.
'm
.
'm
.
.
'll
.
'factory
'
'm
'm
.
?
'm
.
.
,
(
:
'm
.
'm
.
.
,
.
.
've
,
.
?
'm
.
.
.
2017.08.11
24:18:54
thread/info
:
've
,
.
'm
.
.
n't
,
n't
,
.
'm
.
?
'm
.
.
$
3.30
$
's
.
've
.
'
'
.
?
'm
.
.
'm
.
.
.
n't
.
'm
.
.
'm
.
'm
.
.
.
.
've
,
n't
.
'm
.
.
,
third-party
.
.
'm
,
's
.
'm
.
.
,
,
've
,
.
'm
.
.
~60-95
,
.
.
's
.
'm
.
.
.
's
.
'm
.
.
.
.
.
'm
.
,
.
've
,
.
?
.
:
'm
.
?
'm
.
.
,
.
n't
.
n't
.
'm
.
.
'd
!
!
r.b
.
.
,
.
'm
.
.
.
've
,
.
.
.
?
web-host
,
.
'm
.
.
,
@
comcast.net
.
.
've
,
.
?
'm
.
.
-
.
``
,
.
.
.
?
's
've
.
'
'
.
?
,
.
?
$
-x
:
//post.pinterest.com/
?
hash=hf
.
n't
.
'm
d.
.
1.00
.
'm
.
'm
.
.
.
!
've
.
've
.
'
'
.
?
'm
.
.
(
)
.
(
)
!
've
,
.
'm
.
.
've
.
'
'
.
?
'm
wi-fi
.
n't
,
.
?
,
.
n't
.
'm
wi-fi
.
n't
,
.
?
've
,
n't
.
'm
.
.
.
,
's
.
's
.
'm
.
.
%
.
'm
,
's
.
'm
d.
.
,
.
$
!
,
.
'm
.
.
01:13:12
thread/error
:
net.minecraft.inventory.itemstack
've
,
.
'm
.
.
—
``
''
.
'm
hardware-related
.
'm
.
.
,
.
'm
.
?
'm
.
.
...
've
,
.
?
've
.
's
.
?
,
1.22
've
.
.
'm
.
.
.
.
'm
,
.
'm
.
.
'm
.
,
.
'm
.
.
,
,
'm
.
,
.
've
.
's
.
?
.
'm
,
.
'm
.
.
.
n't
.
''
``
''
've
,
.
'm
.
.
*
/
this.productversion
=
``
''
:
``
''
,
``
''
:
``
$
0.99
''
,
'm
hardware-related
.
'm
.
.
,
.
.
-pav
+
've
,
.
?
'm
.
.
14.2.5.2
(
4.1
)
(
)
.
14.2.5.3
,
.
'm
.
.
(
/r/bundles
,
.
)
've
,
.
'm
.
.
.
.
.
've
,
,
n't
.
'm
.
,
.
?
.
'm
,
.
'm
.
.
(
!
)
n't
,
bug-fixing
've
,
.
'm
.
.
.
.
,
.
,
.
,
.
've
.
's
.
?
-
>
-
>
&
've
,
,
,
.
'm
.
.
!
,
've
.
'm
.
,
.
?
'm
.
'm
.
.
'm
.
.
6.7.6
,
,
.
'm
.
.
.
've
.
,
've
.
'm
.
.
,
1.5mm
.
,
's
.
'm
.
.
,
.
've
.
'm
d.
.
.
.
-
,
(
)
'm
hardware-related
.
'm
.
.
've
,
.
'm
.
.
.
.
,
.
*
've
,
.
'm
.
.
:
//help.amazon.com/product-information-qa-b
&
amp=4b093847f4b29d096f15
's
.
've
.
's
.
?
,
'm
hardware-related
.
'm
.
.
4.
,
.
.
'm
.
,
.
'm
.
.
5.1.
.
,
,
've
,
,
,
.
'm
.
.
(
)
'm
.
,
.
'm
.
.
product.
``
``
've
,
.
.
.
?
n't
've
,
.
.
.
?
(
.
n't
've
,
.
'm
wi-fi
.
n't
,
.
?
,
've
,
.
?
'm
.
.
reddit.org
.
'm
hardware-related
.
've
.
's
.
?
.
,
'm
.
,
.
'm
d.
.
.
,
n't
(
've
,
.
'm
.
.
'm
.
$
,
n't
've
,
.
'm
.
.
(
;
'name
'
.
)
(
,
've
,
.
'm
.
.
.
.
've
,
.
'm
.
.
!
''
,
've
,
,
,
.
'm
.
.
.
,
.
,
,
.
'm
.
.
.
!
've
,
.
.
.
?
,
b.
``
'm
.
?
'm
.
.
.
?
've
,
.
've
,
.
?
've
,
'm
,
.
'm
.
assist.
``
``
.
.
've
.
'
'
.
?
'm
.
.
've
've
.
'm
.
.
.
.
1.3
:
-
've
.
,
.
?
!
0.8.10
,
0.8.9
,
0.
'm
.
?
'm
d.
.
.
(
5-12-2013
,
04:27
)
:
've
,
.
'm
.
.
,
.
.
n't
.
'm
.
.
(
)
(
)
(
)
(
've
.
'm
.
.
company-funded
,
.
've
,
,
n't
.
'm
.
.
<
for=
''
'm
hardware-related
.
'm
wi-fi
.
n't
,
.
?
've
,
.
'm
.
.
•
've
.
3-4
've
,
.
'm
.
.
.
've
,
,
,
.
'm
.
.
.
're
.
'm
.
'm
.
.
<
<
.
<
<
've
.
've
,
.
?
's
'm
.
,
.
'm
.
.
-
.
.
've
,
,
n't
.
've
,
.
?
n't
.
've
,
.
'm
.
.
're
.
''
's
,
,
've
,
,
n't
.
'm
.
.
've
.
,
'm
's
.
'm
.
.
—
(
@
)
,
.
n't
.
'm
.
.
.
.
$
15-40
.
sale-priced
've
.
.
'm
.
.
(
)
,
's
.
.
.
?
,
've
.
'
'
.
?
'm
.
.
're
.
's
``
''
.
've
.
.
.
.
?
read-only
've
,
,
n't
.
've
.
's
.
?
:
//patch.ubuntu.com
's
.
,
.
?
'm
.
,
.
'm
.
.
,
1-800-838-8847
,
'm
've
,
.
'm
.
.
's
.
's
've
,
,
n't
.
,
.
?
:
//www.pipeworks.com/blogs/darl-stanton-
've
,
.
?
.
,
'm
.
?
3.
're
n't
.
n't
.
'm
.
.
?
.
:
've
,
,
n't
.
'm
.
.
-
e-mail
,
i.e
.
e-mail
.
-
'm
,
.
'm
.
.
1-800-266-3538.
,
(
)
856-00
've
,
.
'm
.
.
,
'll
.
's
.
'm
.
.
:
:shared
;
:
:id
;
(
)
've
,
.
,
.
?
(
,
'll
'm
.
,
.
'm
wi-fi
.
n't
,
.
?
've
,
n't
.
'm
wi-fi
.
n't
,
.
?
10-
'm
.
'm
.
.
:
.
,
.
'm
,
's
.
'm
.
.
.
''
,
pre-order
've
.
'm
.
'invalid
'
,
'm
.
?
'm
,
.
've
,
.
?
)
$
'll
'm
.
,
.
'm
.
.
.
've
,
.
'm
.
.
<
type=
''
''
id=
''
've
.
'
'
.
?
.
,
.
?
:
?
:
've
,
.
'm
.
.
n't
.
's
.
're
've
,
.
'm
.
.
's
.
'm
.
,
.
?
:
's
``
''
's
.
'm
.
.
?
.
'm
.
?
'm
.
.
's
.
?
1.
$
've
,
.
'm
.
'invalid
'
,
'm
.
?
've
,
.
've
,
.
?
.
'm
.
.
.
'm
.
'm
.
.
've
.
'
'
.
?
.
,
'm
.
?
've
'm
.
?
'm
.
.
...
've
.
'
'
.
?
'm
.
.
'm
.
?
've
.
.
?
'm
.
?
'm
.
'invalid
'
,
'm
.
?
's
.
'm
.
.
'll
,
.
.
!
's
.
'm
.
.
.
:
:
//www.bought-at-amazon.com
.
've
,
,
n't
.
'm
.
.
,
.
,
'm
,
's
.
'm
.
.
-f
,
've
,
.
'm
.
.
(
5.2
)
.
/u/cjguy29
.
4.0
(
8.5
)
.
's
.
'm
wi-fi
.
n't
,
.
?
've
,
.
'm
.
.
,
.
,
:
-
've
,
n't
.
'm
.
.
.
/
.
.
'm
,
's
.
'm
.
.
3.0.5
n't
,
.
'm
.
?
'm
.
.
.
.
,
.
,
.
,
.
've
,
.
'm
.
.
.
''
've
.
'
'
.
?
'm
.
.
(
)
,
:
(
)
(
)
've
,
.
,
.
?
.
've
,
.
?
'm
.
.
,
,
's
'm
,
's
.
'm
wi-fi
.
n't
,
.
?
.
n't
.
'm
.
.
$
1.99
,
.
.
n't
.
'm
.
.
n't
,
.
-
upgrade/rename
.
.
'm
.
,
.
'm
.
.
?
,
've
,
,
n't
.
'm
.
.
.
.
've
.
'
'
.
?
'm
.
.
09/29/2017
10:39:40
id=2
11/1/2017
8:44speaking
've
,
.
'm
.
.
's
,
'm
's
(
)
.
've
.
.
'm
.
.
.
``
've
.
.
'm
.
.
!
<
name=
''
''
style=
``
.text-align
:
;
've
,
.
.
.
?
n't
web-
'm
.
,
.
'm
.
.
•please
:
(
)
541-6550
(
)
785-3180
(
'm
.
,
.
'm
.
.
've
,
.
.
.
?
!
.
've
.
.
'm
.
.
'm
.
.
'm
.
,
.
'm
.
.
!
.
's
.
'm
.
..
n't
.
n't
.
n't
've
,
n't
.
'm
.
.
'm
.
...
'm
.
'm
.
.
*
.
(
,
``
'm
.
?
'm
.
.
'm
.
1.5
.
n't
.
,
.
?
!
.
,
'm
've
,
.
'm
.
.
.
.
've
.
.
'm
.
,
.
?
.
?
's
.
'm
.
.
:
//help.fitnesscouch.com/support/help
.
n't
.
'm
d.
.
:
$
16.01
:
:
:
'm
.
'm
.
.
.
:
're
,
mr.
,
've
,
.
'm
.
.
.
'm
.
.
'm
.
've
,
.
'm
.
.
,
.
!
-a.s.l.s
.
've
,
.
'm
.
.
$
.
.
've
,
.
've
,
.
?
,
s.
've
,
,
n't
.
'm
.
.
(
)
2017-04-03t02:43:49z
'm
,
.
'm
.
.
.
.
've
.
'
'
.
?
'm
.
.
've
,
.
.
.
?
.
.
n't
.
'm
.
,
.
?
.
?
've
,
.
'm
wi-fi
.
n't
,
.
?
:
:
//support/
've
,
.
'm
.
.
.
12-24
(
're
've
,
,
n't
.
'm
.
.
(
)
$
.
.
(
've
.
'm
.
.
,
'm
,
,
've
,
.
?
'm
.
assist.
``
—
a.o
.
a.o
.
.
a.o
've
,
.
?
'm
.
.
,
/b
>
<
'm
.
,
.
.
.
?
'm
,
.
'm
.
.
's
.
,
-o
:
's
.
'm
wi-fi
.
n't
,
.
?
've
,
n't
.
'm
wi-fi
.
n't
,
.
?
've
,
.
'm
.
.
?
``
``
//
n't
've
,
n't
.
.
.
?
,
.
n't
.
'm
.
.
've
,
.
'm
.
'invalid
'
,
'm
.
?
've
,
,
n't
.
'm
.
.
2016-12-02
08:44:20
:
30.125
(
)
1.
'm
hardware-related
.
've
.
.
?
.
n't
.
'm
.
.
:
:
:
:
$
99.99
in-store
'm
hardware-related
.
'm
.
.
.
:
.
'm
.
,
.
'm
.
.
,
i.e
.
,
,
'm
.
'm
.
.
've
.
.
'm
.
.
,
,
've
,
.
'm
.
.
'll
.
've
,
.
'm
.
.
,
've
'm
.
've
,
.
'm
.
'invalid
'
,
'm
.
?
's
.
'm
.
.
've
n't
.
've
,
.
've
,
.
?
``
''
.
n't
.
.
.
?
'm
.
,
've
,
n't
.
'm
.
.
.
.
'm
hardware-related
.
.
.
?
:
)
0.1
've
.
'm
d.
.
,
n't
.
've
,
.
'm
.
.
'll
.
.
've
,
.
'm
.
.
-
.
.
.
've
,
.
'm
.
.
,
'll
.
,

In [28]:
preprocessed_data

[' i have an issue with the gopro hero please assist your bill zip code be we appreciate that you have request a website address please double check your email address i try troubleshoot step mention in the user manual but the issue persist',
 ' i have an issue with the lg smart tv please assist if you need to change an exist product i have an issue with the lg smart tv please assist if the issue i face be intermittent sometimes it work fine but other time it act up unexpectedly',
 ' i face a problem with my dell xps the dell xps be not turn on it be work fine until yesterday but now it do respond i really i use the original charger that come with my dell xps but it not charge properly',
 ' i have an issue with the microsoft office please assist if you have a problem you interest in and i love to see this happen please check out the feedback i already contact customer support multiple time but the issue remain unresolved',
 ' i have an issue with the autodesk autocad please assist note the seller be not responsible for any damage arise out of the delivery of the battleground game please have the game in good condition and ship to you i notice a sudden decrease in battery life on my autodesk autocad it use to last much longer',
 ' i face a problem with my microsoft office the microsoft office be not turn on it be work fine until yesterday but now it do respond to remove the new microsoft office but there be none',
 ' i unable to access my microsoft surface account it keep display an credential error even though i use the correct login information how can i regain access to my account solution 1 i unable to find the option to perform the desire action in the microsoft surface could you please guide me through the step',
 ' i have an issue with the philip hue light please assist thank i will contact all my supplier and confirm please try and find out whether their inventory be currently stock or any other reason i be i perform a factory reset on my philip hue light hop it would resolve the problem but it do help',
 ' i have an issue with the fitbit versa smartwatch please assist thank you fitbit versa smartwatch be not the exact type you might prefer they use the exact same method for different use please help i recently update the firmware of my fitbit versa smartwatch and the issue start happen afterward could it be relate to the update',
 ' my dyson vacuum cleaner be make strange noise and not function properly i suspect there might be a hardware issue can you please help me with this if we can please send a request to dav the issue i face be intermittent sometimes it work fine but other time it act up unexpectedly',
 ' i have an issue with the nintendo switch please assist product search what new in report feedback customer service be your best i use the original charger that come with my nintendo switch but it not charge properly',
 ' i have an issue with the microsoft xbox controller please assist it be possible that we can not find some type of text or a product name to identify someone like brown on the i review the troubleshoot step on the official support website but they do resolve the problem',
 ' i have an issue with the nintendo switch pro controller please assist cqw why do i send him the invoice thank a lot l he like the best customer i meet i notice that the issue occur consistently when i use a specific feature or application on my nintendo switch pro controller',
 ' i recently set up my nest thermostat but it fail to connect to any available network what step should i take to troubleshoot this issue i ca find the ip field of the i concern about the security of my nest thermostat and would like to ensure that my data be safe',
 ' i have an issue with the sony playstation please assist product name tpubask3e3kq0 join date oct 2007 post quote i recently update the firmware of my sony playstation and the issue start happen afterward could it be relate to the update',
 ' i have an issue with the gopro action camera please assist please note you might have already pay for this product which mean spectator be not buy any of the product from the sale a their donation will go straight i notice a sudden decrease in battery life on my gopro action camera it use to last much longer',
 ' i have an issue with the xbox please assist acknowledgement thank to dan for the tip when you purchase a new product from my store or from your local retailer they will also provide i concern about the security of my xbox and would like to ensure that my data be safe',
 ' i have an issue with the microsoft xbox controller please assist thank 0 0 0 0 if this product be sell and you have not use any i review the troubleshoot step on the official support website but they do resolve the problem',
 ' i have an issue with the lg wash machine please assist i want to be an active member of our community on youtube the issue i face be intermittent sometimes it work fine but other time it act up unexpectedly',
 ' i have an issue with the canon eos please assist i have an issue with the product purchase please assist customer reviewer my husband be able to take an order from apple i check for any available software update for my canon eos but there be none',
 ' i have an issue with the hp pavilion please microsoft surface i check for any available software update for my hp pavilion but there be none',
 ' i have an issue with the fitbit versa smartwatch please assist the email address should change to customer a there be a unique id number unique for each product you i try different setting and configuration on my fitbit versa smartwatch but the issue persist',
 ' i have an issue with the xbox please assist and if need be this time that could help update my version to or more the issue i face be intermittent sometimes it work fine but other time it act up unexpectedly',
 ' i have an issue with the nintendo switch pro controller please assist i take care of those i perform a factory reset on my nintendo switch pro controller hop it would resolve the problem but it do help',
 ' i have an issue with the amazon kindle please assist amazon kindle do not represent the price which you receive by the day immediately before the shipment date in many case this be the i notice a sudden decrease in battery life on my amazon kindle it use to last much longer',
 ' my hp pavilion be make strange noise and not function properly i suspect there might be a hardware issue can you please help me with this thank you thank you for post it take me a i experience this issue on multiple device of the same model so it seem to be a widespread problem',
 ' i encounter a software bug in the lenovo thinkpad whenever i try to perform a specific action the application crash be there any update or fix available on window vista this be not possible if you be i perform a factory reset on my lenovo thinkpad hop it would resolve the problem but it do help',
 ' i have an issue with the fitbit charge please assist fitbit charge must be a valid email address for your order and be valid for one week in advance please make your purchase a quickly a possible the issue i face be intermittent sometimes it work fine but other time it act up unexpectedly',
 ' i have an issue with the fitbit charge please assist thank you a statement from the consumer group have be release by microsoft late on tuesday afternoon the purchase of this product be make use a contract with i use the original charger that come with my fitbit charge but it not charge properly',
 ' i have an issue with the xbox please assist it not possible to remove the miss content i already contact customer support multiple time but the issue remain unresolved',
 ' i have an issue with the adobe photoshop please assist i use a brand new product what a strange situation i just purchase a brand new one what to do i notice that the issue occur consistently when i use a specific feature or application on my adobe photoshop',
 ' i have an issue with the gopro action camera please assist the seller have sell the item for when we receive your replacement we will exchange the item for a full refund or exchange immediately upon i already contact customer support multiple time but the issue remain unresolved',
 ' i notice a software bug in the fitbit charge app it cause data loss and unexpected error how can i resolve this issue i need assistance a soon a possible because it affect my work and productivity',
 ' i have an issue with the autodesk autocad please assist we hope that every vendor take the time it take in to do the follow remove the product from your account notify consumer call them make their i concern about the security of my autodesk autocad and would like to ensure that my data be safe',
 ' i have an issue with the microsoft xbox controller please assist we be in the first day at the microsoft xbox controller please assist please assist u i recently update the firmware of my microsoft xbox controller and the issue start happen afterward could it be relate to the update',
 ' i recently set up my gopro hero but it fail to connect to any available network what step should i take to troubleshoot this issue if you know the answer please let me know do i i notice a sudden decrease in battery life on my gopro hero it use to last much longer',
 ' i have an issue with the canon eos please assist i have to ask for support from you the customer before the item arrival and i ca do that in the short term will you pay me i follow the troubleshoot step mention in the user manual but the issue persist',
 ' i forget my password for my amazon kindle account and the password reset option be not work how can i recover my account i can reset my password by enter the follow my password still valid password be expire i recently update the firmware of my amazon kindle and the issue start happen afterward could it be relate to the update',
 ' i have an issue with the google pixel please assist do i need to purchase a refund there be a way to purchase a refund from zerohits but there not a i unable to find the option to perform the desire action in the google pixel could you please guide me through the step',
 ' i have an issue with the amazon echo please assist i have a new account in the system and a new user i have this issue error i concern about the security of my amazon echo and would like to ensure that my data be safe',
 ' i recently set up my playstation but it fail to connect to any available network what step should i take to troubleshoot this issue the next step be to resolve this issue if the user be not i notice that the issue occur consistently when i use a specific feature or application on my playstation',
 ' i face a problem with my dell xps the dell xps be not turn on it be work fine until yesterday but now it do respond if i just switch to a the issue i face be intermittent sometimes it work fine but other time it act up unexpectedly',
 ' i have an issue with the samsung galaxy please assist the product purchase attribute do not exist on your user product this be so that you can configure the samsung galaxy i need assistance a soon a possible because it affect my work and productivity',
 ' i have an issue with the iphone please assist thank you the issue occur after amazon start a tool to deal with a problem like this see page 36 of the faq the product be not i recently update the firmware of my iphone and the issue start happen afterward could it be relate to the update',
 ' i have an issue with the hp pavilion please assist i want a picture for my 3d but i already buy a lot of item so i find an online cart fountain of dream collection i unable to find the option to perform the desire action in the hp pavilion could you please guide me through the step',
 ' i have an issue with the lg smart tv please assist thank a a result i have an issue with the patch please assist all i ask be to update i concern about the security of my lg smart tv and would like to ensure that my data be safe',
 ' i have an issue with the nintendo switch pro controller please assist we have not yet provide an address or a name for this product if this website do not exist please contact u with this information and we will provide it i need assistance a soon a possible because it affect my work and productivity',
 ' i have an issue with the gopro hero please assist this product be not find on and should not come from this site not sure about what this product cover product description i experience this issue on multiple device of the same model so it seem to be a widespread problem',
 ' i have an issue with the lg oled please assist please do do see my issue please contact me i unable to find the option to perform the desire action in the lg oled could you please guide me through the step',
 ' i have an issue with the microsoft office please assist if you receive a refund please contact customer service otherwise please call u at i have an issue with the i concern about the security of my microsoft office and would like to ensure that my data be safe',
 ' i encounter a software bug in the sony xperia whenever i try to perform a specific action the application crash be there any update or fix available there be several package that run in memory by default these i experience this issue on multiple device of the same model so it seem to be a widespread problem',
 ' i recently set up my lg smart tv but it fail to connect to any available network what step should i take to troubleshoot this issue 1 visit http i review the troubleshoot step on the official support website but they do resolve the problem',
 ' i have an issue with the nest thermostat please assist please please i need assistance a soon a possible because it affect my work and productivity',
 ' i have an issue with the hp pavilion please assist if it not work i ca help you i perform a factory reset on my hp pavilion hop it would resolve the problem but it do help',
 ' i notice a software bug in the microsoft xbox controller app it cause data loss and unexpected error how can i resolve this issue for those who live in the you can use the microsoft xbox controller could you please guide me through the step',
 ' i have an issue with the nintendo switch pro controller please assist the request address will be return within 3 9 business day please do not hesitate to contact u use the appropriate form 9 week from purchase time i unable to find the option to perform the desire action in the nintendo switch pro controller could you please guide me through the step',
 ' i have an issue with the autodesk autocad please assist i notice that the issue occur consistently when i use a specific feature or application on my autodesk autocad',
 ' i have an issue with the gopro action camera please assist thank you this product be add to your friend shop cart at your friend favorite store sorry your account be not load i follow the troubleshoot step mention in the user manual but the issue persist',
 ' i forget my password for my autodesk autocad account and the password reset option be not work how can i recover my account what happen when you lose all of your money without a credit card the issue i face be intermittent sometimes it work fine but other time it act up unexpectedly',
 ' i have an issue with the apple airpods please assist also note your information get delete every time an article be send to a website you never view product id be a unique identifier in i not sure if this issue be specific to my device or if others have report similar problem',
 ' i have an issue with the sony 4k hdr tv please assist it time for me to update the product list i have an issue with thesony 4k hdr tv please assist it time for i perform a factory reset on my sony 4k hdr tv hop it would resolve the problem but it do help',
 ' i have an issue with the lenovo thinkpad please assist i be able to get my 50 bag from the vendor but the bag i be wear in the show be cover in sticker and the price for those i try different setting and configuration on my lenovo thinkpad but the issue persist',
 ' i have an issue with the xbox please assist function getproductcount orters function p this get the count for all the item in the the issue i face be intermittent sometimes it work fine but other time it act up unexpectedly',
 ' i have an issue with the adobe photoshop please assist add a custom app icon to the app window click app manager you see a list of all of the new apps i check the device setting and make sure that everything be configure correctly',
 ' i face a problem with my microsoft xbox controller the microsoft xbox controller be not turn on it be work fine until yesterday but now it do respond i work around this problem by switch off i notice a peculiar error message pop up on my microsoft xbox controller screen it say error message what do it mean',
 ' there seem to be a glitch in the apple airpods software it freeze frequently make it difficult to use can you please provide a solution i love to do this on my own it a i notice a peculiar error message pop up on my apple airpods screen it say error message what do it mean',
 ' i notice a software bug in the gopro hero app it cause data loss and unexpected error how can i resolve this issue a good way to resolve this software issue be to use a custom configuration file the issue i face be intermittent sometimes it work fine but other time it act up unexpectedly',
 ' i accidentally delete important data from my microsoft office be there any way to recover the delete file i need them urgently what can i do to recover them product purchase be never recoverable from the database i worry that the issue might be and might require repair or replacement',
 ' i have an issue with the adobe photoshop please assist if your product be purchase with the adobe photoshop the adobe photoshop will be refund 7 pay it i perform a factory reset on my adobe photoshop hop it would resolve the problem but it do help',
 ' i unable to access my canon dslr camera account it keep display an credential error even though i use the correct login information how can i regain access to my account if you do i concern about the security of my canon dslr camera and would like to ensure that my data be safe',
 ' i accidentally delete important data from my google pixel be there any way to recover the delete file i need them urgently what about my search file the google pixel be the i use the original charger that come with my google pixel but it not charge properly',
 ' i recently set up my iphone but it fail to connect to any available network what step should i take to troubleshoot this issue i try clear the cache and data for the iphone app but the issue persist',
 ' i have an issue with the dyson vacuum cleaner please assist when i first notice dyson vacuum cleaner the new price of the book be too high i already send out the refund request but they will i check for software update and my dyson vacuum cleaner be already run the latest version',
 ' my fitbit charge be make strange noise and not function properly i suspect there might be a hardware issue can you please help me with this this be a product that must fit in a box please let me i notice a peculiar error message pop up on my fitbit charge screen it say error message what do it mean',
 ' i have an issue with the xbox please assist please take care of such request 1 2 the be make up with specific i check the device setting and make sure that everything be configure correctly',
 ' i have an issue with the roomba robot vacuum please assist it be not allow to purchase a product from an individual or for a company in which there be no specific employee or employee and all product have to i follow the troubleshoot step mention in the user manual but the issue persist',

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
vectorizer.fit(preprocessed_data)

CountVectorizer()

In [31]:
vectorizer.vocabulary_

{'have': 1985,
 'an': 481,
 'issue': 2265,
 'with': 4601,
 'the': 4157,
 'gopro': 1909,
 'hero': 2016,
 'please': 3129,
 'assist': 576,
 'your': 4687,
 'bill': 727,
 'zip': 4703,
 'code': 1009,
 'be': 692,
 'we': 4531,
 'appreciate': 533,
 'that': 4152,
 'you': 4684,
 'request': 3511,
 'website': 4538,
 'address': 393,
 'double': 1418,
 'check': 939,
 'email': 1503,
 'try': 4298,
 'troubleshoot': 4290,
 'step': 3979,
 'mention': 2623,
 'in': 2136,
 'user': 4404,
 'manual': 2556,
 'but': 838,
 'persist': 3067,
 'lg': 2448,
 'smart': 3859,
 'tv': 4307,
 'if': 2106,
 'need': 2775,
 'to': 4233,
 'change': 926,
 'exist': 1605,
 'product': 3248,
 'face': 1642,
 'intermittent': 2212,
 'sometimes': 3883,
 'it': 2268,
 'work': 4615,
 'fine': 1708,
 'other': 2946,
 'time': 4220,
 'act': 368,
 'up': 4384,
 'unexpectedly': 4345,
 'problem': 3238,
 'my': 2739,
 'dell': 1274,
 'xps': 4663,
 'not': 2829,
 'turn': 4305,
 'on': 2903,
 'until': 4380,
 'yesterday': 4678,
 'now': 2840,
 'do': 1395,
 'respond': 3535,
 'really': 3405,
 'use': 4402,
 'original': 2940,
 'charger': 933,
 'come': 1025,
 'charge': 932,
 'properly': 3288,
 'microsoft': 2644,
 'office': 2884,
 'interest': 2209,
 'and': 486,
 'love': 2512,
 'see': 3707,
 'this': 4196,
 'happen': 1970,
 'out': 2951,
 'feedback': 1685,
 'already': 462,
 'contact': 1087,
 'customer': 1182,
 'support': 4058,
 'multiple': 2730,
 'remain': 3477,
 'unresolved': 4371,
 'autodesk': 623,
 'autocad': 622,
 'note': 2830,
 'seller': 3714,
 'responsible': 3538,
 'for': 1746,
 'any': 505,
 'damage': 1205,
 'arise': 551,
 'of': 2880,
 'delivery': 1273,
 'battleground': 687,
 'game': 1827,
 'good': 1901,
 'condition': 1056,
 'ship': 3778,
 'notice': 2834,
 'sudden': 4039,
 'decrease': 1254,
 'battery': 685,
 'life': 2455,
 'last': 2410,
 'much': 2729,
 'longer': 2500,
 'remove': 3487,
 'new': 2785,
 'there': 4180,
 'none': 2820,
 'unable': 4328,
 'access': 348,
 'surface': 4063,
 'account': 357,
 'keep': 2349,
 'display': 1375,
 'credential': 1154,
 'error': 1558,
 'even': 1574,
 'though': 4201,
 'correct': 1115,
 'login': 2493,
 'information': 2167,
 'how': 2063,
 'can': 868,
 'regain': 3454,
 'solution': 3876,
 'find': 1707,
 'option': 2928,
 'perform': 3059,
 'desire': 1298,
 'action': 369,
 'could': 1124,
 'guide': 1951,
 'me': 2598,
 'through': 4208,
 'philip': 3086,
 'hue': 2074,
 'light': 2457,
 'thank': 4149,
 'will': 4588,
 'all': 449,
 'supplier': 4056,
 'confirm': 1064,
 'whether': 4566,
 'their': 4167,
 'inventory': 2230,
 'currently': 1177,
 'stock': 3986,
 'or': 2930,
 'reason': 3406,
 'factory': 1646,
 'reset': 3522,
 'hop': 2053,
 'would': 4628,
 'resolve': 3529,
 'help': 2008,
 'fitbit': 1722,
 'versa': 4460,
 'smartwatch': 3861,
 'exact': 1584,
 'type': 4316,
 'might': 2648,
 'prefer': 3198,
 'they': 4190,
 'same': 3638,
 'method': 2636,
 'different': 1331,
 'recently': 3417,
 'update': 4386,
 'firmware': 1714,
 'start': 3963,
 'afterward': 421,
 'relate': 3468,
 'dyson': 1454,
 'vacuum': 4425,
 'cleaner': 983,
 'make': 2541,
 'strange': 3997,
 'noise': 2814,
 'function': 1802,
 'suspect': 4070,
 'hardware': 1976,
 'send': 3717,
 'dav': 1223,
 'nintendo': 2808,
 'switch': 4081,
 'search': 3697,
 'what': 4558,
 'report': 3503,
 'service': 3737,
 'best': 716,
 'xbox': 4643,
 'controller': 1096,
 'possible': 3170,
 'some': 3878,
 'text': 4146,
 'name': 2755,
 'identify': 2103,
 'someone': 3880,
 'like': 2458,
 'brown': 811,
 'review': 3558,
 'official': 2886,
 'pro': 3236,
 'cqw': 1141,
 'why': 4578,
 'him': 2029,
 'invoice': 2236,
 'lot': 2510,
 'he': 1990,
 'meet': 2615,
 'occur': 2874,
 'consistently': 1082,
 'when': 4562,
 'specific': 3915,
 'feature': 1680,
 'application': 530,
 'set': 3740,
 'nest': 2778,
 'thermostat': 4182,
 'fail': 1647,
 'connect': 1071,
 'available': 632,
 'network': 2782,
 'should': 3794,
 'take': 4101,
 'ca': 848,
 'ip': 2240,
 'field': 1694,
 'concern': 1054,
 'about': 339,
 'security': 3706,
 'ensure': 1536,
 'data': 1217,
 'safe': 3627,
 'sony': 3889,
 'playstation': 3126,
 'tpubask3e3kq0': 4264,
 'join': 2315,
 'date': 1221,
 'oct': 2875,
 '2007': 138,
 'post': 3172,
 'quote': 3370,
 'camera': 866,
 'pay': 3033,
 'which': 4567,
 'mean': 2600,
 'spectator': 3918,
 'buy': 840,
 'from': 1790,
 'sale': 3633,
 'donation': 1411,
 'go': 1898,
 'straight': 3994,
 'acknowledgement': 363,
 'dan': 1206,
 'tip': 4225,
 'purchase': 3326,
 'store': 3991,
 'local': 2486,
 'retailer': 3551,
 'also': 463,
 'provide': 3299,
 'sell': 3713,
 'wash': 4523,
 'machine': 2531,
 'want': 4515,
 'active': 372,
 'member': 2618,
 'our': 2950,
 'community': 1036,
 'youtube': 4690,
 'canon': 876,
 'eos': 1548,
 'reviewer': 3559,
 'husband': 2085,
 'able': 338,
 'order': 2932,
 'apple': 527,
 'software': 3874,
 'hp': 2066,
 'pavilion': 3031,
 'unique': 4355,
 'id': 2099,
 'number': 2851,
 'each': 1455,
 'setting': 3745,
 'configuration': 1062,
 'version': 4462,
 'more': 2708,
 'care': 883,
 'those': 4199,
 'amazon': 474,
 'kindle': 2372,
 'represent': 3505,
 'price': 3221,
 'receive': 3413,
 'by': 844,
 'day': 1229,
 'immediately': 2124,
 'before': 699,
 'shipment': 3779,
 'many': 2561,
 'case': 892,
 'experience': 1611,
 'device': 1313,
 'model': 2690,
 'so': 3870,
 'seem': 3708,
 'widespread': 4582,
 'encounter': 1519,
 'bug': 827,
 'lenovo': 2441,
 'thinkpad': 4193,
 'whenever': 4563,
 'crash': 1144,
 'fix': 1726,
 'window': 4592,
 'vista': 4489,
 'must': 2736,
 'valid': 4428,
 'one': 2907,
 'week': 4543,
 'advance': 406,
 'quickly': 3364,
 'statement': 3967,
 'consumer': 1086,
 'group': 1939,
 'release': 3472,
 'late': 2412,
 'tuesday': 4302,
 'afternoon': 420,
 'contract': 1094,
 'miss': 2674,
 'content': 1090,
 'adobe': 402,
 'photoshop': 3092,
 'brand': 793,
 'situation': 3833,
 'just': 2334,
 'item': 2270,
 'replacement': 3498,
 'exchange': 1593,
 'full': 1798,
 'refund': 3451,
 'upon': 4390,
 'app': 520,
 'cause': 901,
 'loss': 2509,
 'unexpected': 4344,
 'assistance': 577,
 'soon': 3890,
 'because': 696,
 'affect': 415,
 'productivity': 3254,
 'hope': 2054,
 'every': 1577,
 'vendor': 4455,
 'follow': 1742,
 'notify': 2836,
 'call': 862,
 'them': 4170,
 'first': 1715,
 'at': 587,
 'know': 2384,
 'answer': 502,
 'let': 2444,
 'ask': 571,
 'arrival': 557,
 'short': 3790,
 'term': 4135,
 'forget': 1753,
 'password': 3020,
 'recover': 3431,
 'enter': 1537,
 'still': 3984,
 'expire': 1616,
 'google': 1905,
 'pixel': 3111,
 'way': 4529,
 'zerohits': 4700,
 'echo': 1472,
 'system': 4091,
 'next': 2793,
 'samsung': 3640,
 'galaxy': 1824,
 'attribute': 600,
 'configure': 1063,
 'iphone': 2242,
 'after': 419,
 'tool': 4249,
 'deal': 1235,
 'page': 2988,
 '36': 205,
 'faq': 1661,
 'picture': 3101,
 '3d': 210,
 'online': 2910,
 'cart': 891,
 'fountain': 1765,
 'dream': 1430,
 'collection': 1017,
 'result': 3548,
 'patch': 3024,
 'yet': 4679,
 'site': 3832,
 'sure': 4062,
 'cover': 1138,
 'description': 1290,
 'oled': 2901,
 'otherwise': 2948,
 'xperia': 4662,
 'several': 3751,
 'package': 2984,
 'run': 3609,
 'memory': 2621,
 'default': 1257,
 'these': 4184,
 'visit': 4487,
 'http': 2072,
 'who': 4573,
 'live': 2477,
 'return': 3555,
 'within': 4604,
 'business': 836,
 'hesitate': 2017,
 'appropriate': 536,
 'form': 1756,
 'add': 384,
 'friend': 1788,
 'shop': 3786,
 'favorite': 1673,
 'sorry': 3896,
 'load': 2483,
 'lose': 2508,
 'money': 2702,
 'without': 4605,
 'credit': 1155,
 'card': 882,
 'airpods': 434,
 'get': 1861,
 'delete': 1268,
 'article': 563,
 'never': 2784,
 'view': 4470,
 'identifier': 2102,
 'others': 2947,
 'similar': 3817,
 '4k': 243,
 'hdr': 1989,
 'list': 2470,
 'thesony': 4185,
 '50': 251,
 'bag': 659,
 'wear': 4532,
 'show': 3796,
 'sticker': 3983,
 'getproductcount': 1865,
 'orters': 2944,
 'count': 1126,
 'custom': 1181,
 'icon': 2098,
 'click': 987,
 'manager': 2552,
 'apps': 540,
 'everything': 1581,
 'correctly': 1116,
 'around': 553,
 'off': 2882,
 'peculiar': 3045,
 'message': 2632,
 'pop': 3158,
 'screen': 3686,
 'say': 3659,
 'glitch': 1890,
 'freeze': 1782,
 'frequently': 1784,
 'difficult': 1332,
 'own': 2969,
 'file': 1698,
 'accidentally': 352,
 'important': 2130,
 'urgently': 4396,
 'recoverable': 3432,
 'database': 1218,
 'worry': 4624,
 'require': 3513,
 'repair': 3494,
 'dslr': 1441,
 'clear': 984,
 'cache': 850,
 'book': 765,
 'too': 4248,
 'high': 2023,
 'latest': 2415,
 'fit': 1721,
 'box': 788,
 'such': 4038,
 'roomba': 3594,
 'robot': 3583,
 'allow': 455,
 'individual': 2160,
 'company': 1037,
 'no': 2812,
 'employee': 1513,
 '25': 164,
 'download': 1422,
 'demo': 1276,
 'rat': 3386,
 'impact': 2126,
 'score': 3681,
 'over': 2960,
 'mogul': 2697,
 'financial': 1705,
 'phone': 3087,
 'while': 4568,
 'wait': 4508,
 'pick': 3099,
 'cable': 849,
 'adapter': 380,
 'peripheral': 3063,
 'hard': 1973,
 'representative': 3506,
 'arrive': 558,
 'may': 2590,
 'keyword': 2361,
 'log': 2490,
 'into': 2221,
 'lock': 2489,
 'unlock': 4364,
 'browser': 813,
 'token': 4240,
 'previous': 3219,
 '12': 68,
 'month': 2706,
 'param': 3002,
 'nikon': 2805,
 'yes': 4677,
 '28': 178,
 '30': 193,
 '32': 200,
 'computer': 1052,
 'power': 3182,
 'source': 3903,
 'open': 2916,
 'router': 3600,
 'wire': 4595,
 'enable': 1517,
 'beware': 720,
 'link': 2464,
 'select': 3710,
 'incorrectly': 2152,
 'recent': 3416,
 'bose': 775,
 'quietcomfort': 3366,
 'here': 2013,
 'additional': 388,
 'always': 472,
 'match': 2579,
 'very': 4463,
 'costly': 1122,
 'remotely': 3485,
 'remote': 3484,
 'think': 4192,
 'maybe': 2591,
 'dns': 1394,
 'query': 3358,
 'location': 2488,
 'overview': 2967,
 'unread': 4368,
 'second': 3700,
 'soundbar': 3901,
 'right': 3573,
 'style': 4019,
 'due': 1444,
 'oversize': 2965,
 'expect': 1608,
 'rely': 3476,
 'heavily': 2002,
 'daily': 1204,
 'task': 4112,
 'hinder': 2031,
 'asus': 584,
 'rog': 3585,
 'remember': 3481,
 'author': 615,
 'understand': 4341,
 'improve': 2133,
 'oririt': 2943,
 'current': 1176,
 'handle': 1967,
 'plan': 3116,
 'fetch': 1690,
 'blockchain': 747,
 'soundlink': 3902,
 'speaker': 3911,
 'establish': 1563,
 'stable': 3951,
 'internet': 2217,
 'connection': 1072,
 'disconnect': 1359,
 'intermittently': 2213,
 'write': 4631,
 'command': 1028,
 'pm': 3142,
 'instruction': 2194,
 'retrieve': 3553,
 'comment': 1029,
 'cance': 870,
 'further': 1809,
 'warranty': 4521,
 'inform': 2166,
 'fill': 1699,
 'pipe': 3108,
 'htmldatahelper': 2071,
 'transfer': 4273,
 'wordpress': 4614,
 'mimi': 2658,
 'amaze': 473,
 'awesome': 640,
 'great': 1927,
 'filter': 1700,
 'put': 3337,
 'back': 649,
 'define': 1260,
 'directx': 1349,
 'bottom': 781,
 'partially': 3009,
 'subvert': 4034,
 'black': 741,
 'contour': 1093,
 'topic': 4251,
 'category': 898,
 'subcategory': 4021,
 'username': 4406,
 'font': 1743,
 'size': 3835,
 'response': 3536,
 'tutorial': 4306,
 'forum': 1760,
 'luck': 2519,
 'far': 1662,
 'info': 2165,
 'zerogel': 4699,
 'year': 4674,
 'ago': 428,
 'flicker': 1733,
 'monitor': 2704,
 'instal': 2186,
 'exactly': 1585,
 'rickj': 3568,
 'document': 1401,
 'disappear': 1353,
 'input': 2176,
 'checkbox': 940,
 'ready': 3399,
 'mailbox': 2535,
 'question': 3359,
 'editor': 1480,
 'refer': 3445,
 'chrome': 955,
 'extension': 1626,
 'market': 2571,
 'puh': 3318,
 'poh': 3149,
 'earlier': 1457,
 'old': 2898,
 'male': 2544,
 'daughter': 1222,
 'mine': 2661,
 'car': 881,
 'less': 2442,
 'expensive': 1610,
 'include': 2145,
 'url': 4397,
 'board': 756,
 '10': 51,
 '11x': 67,
 '14': 85,
 '13': 76,
 'nothing': 2832,
 'else': 1500,
 'btw': 821,
 'pretty': 3215,
 'hand': 1966,
 'anything': 509,
 'line': 2463,
 'pain': 2989,
 'maintainer': 2539,
 'course': 1134,
 'userbase': 4405,
 'mind': 2660,
 'small': 3857,
 'possibility': 3169,
 'stick': 3982,
 'srudmell': 3944,
 'future': 1811,
 'apologize': 518,
 'vaporizer': 4437,
 'improvement': 2134,
 'minor': 2667,
 'cosmetic': 1119,
 'admin': 397,
 'two': 4313,
 'break': 797,
 'heart': 2000,
 'tomorrow': 4246,
 'proper': 3287,
 'feel': 1686,
 'free': 1778,
 'suggest': 4043,
 'helpful': 2009,
 'below': 708,
 'idea': 2100,
 'behave': 702,
 'where': 4564,
 'restore': 3546,
 'share': 3765,
 'example': 1586,
 'garmin': 1834,
 'forerunner': 1751,
 'strategy': 3998,
 'tracker': 4266,
 'sign': 3809,
 'little': 2476,
 'thing': 4191,
 'happy': 1972,
 'easy': 1468,
 'few': 1692,
 'javascript': 2290,
 'hold': 2043,
 'shift': 3775,
 'key': 2358,
 'client': 988,
 'chat': 935,
 'touhoumon': 4257,
 'touhoubon': 4256,
 's1t1d': 3620,
 'huge': 2076,
 'york': 4681,
 'ny': 2860,
 'westfield': 4555,
 'fieldhouse': 1695,
 'macbook': 2530,
 'copy': 1107,
 'aware': 638,
 'place': 3114,
 'obtain': 2871,
 'however': 2064,
 'choose': 952,
 'offer': 2883,
 'disable': 1352,
 'trouble': 4288,
 'home': 2048,
 'detect': 1307,
 'although': 470,
 'polite': 3155,
 'aggressive': 427,
 'probably': 3237,
 'wo': 4608,
 'play': 3122,
 'deliver': 1272,
 'customise': 1185,
 'create': 1149,
 'inc': 2142,
 '37': 207,
 'indicate': 2158,
 'setup': 3749,
 'server': 3736,
 'determine': 1308,
 'provider': 3300,
 'goal': 1899,
 'dec': 1245,
 '10th': 59,
 'three': 4205,
 'something': 3881,
 'title': 4229,
 'ui': 4324,
 'section': 3702,
 'uipybar': 4325,
 'potato': 3175,
 'influence': 2164,
 '26': 171,
 'sep': 3726,
 'shoe': 3784,
 'dress': 1432,
 'glove': 1894,
 'various': 4443,
 'retail': 3550,
 'outlet': 2954,
 'attempt': 596,
 'begin': 700,
 'give': 1883,
 'backer': 651,
 'invest': 2232,
 'wrong': 4633,
 'later': 2414,
 'depend': 1282,
 'capability': 879,
 'initial': 2172,
 'purchaser': 3330,
 'desktop': 1300,
 'external': 1629,
 'drive': 1434,
 'printer': 3228,
 'cd': 907,
 'dvd': 1452,
 'player': 3124,
 'save': 3655,
 'cost': 1120,
 'cash': 894,
 'figure': 1697,
 '100': 52,
 'rob': 3581,
 'mec': 2606,
 'talk': 4103,
 'everyone': 1580,
 'mara': 2565,
 'process': 3242,
 'again': 422,
 'hour': 2061,
 '24': 161,
 'curl': 1174,
 'word': 4613,
 'only': 2911,
 'jvc': 2336,
 'warehouse': 4516,
 'auction': 603,
 'street': 4002,
 'brooklyn': 809,
 'museum': 2732,
 'then': 4174,
 'minute': 2671,
 'value': 4431,
 'subscribe': 4025,
 'unsubscribe': 4378,
 'immediate': 2123,
 'payment': 3035,
 'collect': 1016,
 'aspiration': 572,
 'mostly': 2711,
 'enough': 1533,
 'ram': 3378,
 'down': 1420,
 'private': 3233,
 'etc': 1565,
 'news': 2791,
 'standard': 3960,
 'recommend': 3425,
 'differenceslist': 1330,
 'read': 3394,
 'volta': 4498,
 'today': 4236,
 '799': 299,
 'once': 2904,
 'continue': 1092,
 'manufacturer': 2559,
 'label': 2393,
 'nor': 2825,
 'ever': 1576,
 'either': 1490,
 'consent': 1076,
 'interference': 2211,
 'eligible': 1498,
 'fee': 1684,
 'language': 2402,
 'button': 839,
 'gift': 1871,
 'touch': 4254,
 'giftcard': 1872,
 'shopper': 3789,
 'restriction': 3547,
 'often': 2889,
 'regard': 3455,
 'michael': 2638,
 'discussion': 1369,
 'donald': 1409,
 'trump': 4294,
 'realdonaldtrump': 3402,
 'january': 2284,
 '2016': 147,
 'campaign': 867,
 'host': 2058,
 '2257': 154,
 'fwy': 1814,
 'se': 3695,
 'west': 4553,
 'ne': 2768,
 'azure': 643,
 'rest': 3540,
 'almost': 456,
 'state': 3966,
 'reflect': 3448,
 'choice': 951,
 'well': 4549,
 'fprintf': 1770,
 'twitter': 4312,
 'facebook': 1643,
 'easter': 1466,
 'upgrade': 4388,
 'disclosure': 1358,
 'ben': 710,
 'witherspoon': 4603,
 'personal': 3069,
 '125': 73,
 '250': 165,
 '500': 252,
 'quantity': 3355,
 'specify': 3917,
 'reply': 3500,
 'edit': 1478,
 'poster': 3174,
 'dredd': 1431,
 'people': 3052,
 'explain': 1618,
 'simple': 3819,
 'stuff': 4014,
 'med': 2610,
 'fault': 1669,
 'chris': 953,
 'nam': 2754,
 'cpu': 1140,
 'look': 2502,
 'policy': 3154,
 'approach': 535,
 'fan': 1658,
 'harder': 1974,
 'tougher': 4255,
 'detail': 1305,
 'shopowner': 3788,
 'complaint': 1044,
 'operational': 2922,
 'install': 2187,
 'meantime': 2602,
 'div': 1386,
 'hear': 1999,
 'devolve': 1314,
 'better': 718,
 'kid': 2368,
 'marketplace': 2572,
 'table': 4094,
 'strongly': 4008,
 'doubt': 1419,
 'scam': 3663,
 'protect': 3293,
 'complete': 1045,
 'summary': 4050,
 'impossible': 2131,
 'locate': 2487,
 'strong': 4007,
 'suggestion': 4044,
 'ability': 337,
 'conn': 1070,
 'apply': 531,
 'department': 1281,
 'sick': 3801,
 'complain': 1043,
 'successfully': 4037,
 'appear': 525,
 'reorder': 3491,
 'confirmation': 1065,
 'significant': 3812,
 'alteration': 466,
 'promotion': 3279,
 'brightness': 805,
 '60': 275,
 'matt': 2585,
 'david': 1224,
 'jerk': 2300,
 'seth': 3741,
 'vissers': 4488,
 'true': 4292,
 'progress': 3273,
 'availability': 631,
 'tell': 4131,
 'end': 1522,
 'water': 4528,
 'skill': 3839,
 'outdated': 2953,
 'rule': 3608,
 'via': 4464,
 'restart': 3541,
 'kevin': 2357,
 'announce': 495,
 'july': 2330,
 '26th': 173,
 'saw': 3657,
 'steal': 3977,
 'metadata': 2634,
 'inadvertently': 2139,
 'isp': 2263,
 ...}

In [34]:
term_doc_mat = vectorizer.transform(data).T 
print(term_doc_mat)

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 242954 stored elements and shape (4708, 8395)>
  Coords	Values
  (393, 0)	2
  (481, 0)	1
  (533, 0)	1
  (576, 0)	1
  (838, 0)	1
  (939, 0)	1
  (1009, 0)	1
  (1418, 0)	1
  (1503, 0)	1
  (1909, 0)	1
  (1985, 0)	1
  (2016, 0)	1
  (2136, 0)	1
  (2265, 0)	2
  (2556, 0)	1
  (3129, 0)	2
  (4152, 0)	1
  (4157, 0)	3
  (4404, 0)	1
  (4531, 0)	1
  (4538, 0)	1
  (4601, 0)	1
  (4684, 0)	1
  (4687, 0)	2
  (4703, 0)	1
  :	:
  (1395, 8394)	1
  (1726, 8394)	1
  (1861, 8394)	1
  (1976, 8394)	1
  (2074, 8394)	1
  (2268, 8394)	2
  (2739, 8394)	2
  (2840, 8394)	1
  (2886, 8394)	1
  (2903, 8394)	1
  (3238, 8394)	2
  (3529, 8394)	1
  (3686, 8394)	1
  (3794, 8394)	1
  (4058, 8394)	1
  (4157, 8394)	4
  (4180, 8394)	1
  (4190, 8394)	1
  (4233, 8394)	3
  (4298, 8394)	1
  (4328, 8394)	1
  (4402, 8394)	1
  (4538, 8394)	1
  (4558, 8394)	1
  (4601, 8394)	1

In [33]:
term_doc_mat.shape

(4708, 8395)

In [2]:
from gensim.utils import simple_preprocess

ModuleNotFoundError: No module named 'gensim'